import type { GalleryPresetFile, ObjGalleryPresetFile } from "../types";
import {
  KHRONOS_FOX_ATTRIBUTION,
  MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION,
  MINI_MIKES_METRO_MINIS_ATTRIBUTION,
  MONOGON_DESERT_TOWN_ATTRIBUTION,
  MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION,
  MONOGON_COUNTRY_SIDE_ATTRIBUTION,
  MONOGON_CYBERPUNK_CITY_ATTRIBUTION,
  MONOGON_VOXEL_PLANE_ATTRIBUTION,
  MONOGON_VOXEL_MECHAS_ATTRIBUTION,
  MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION,
  SONA_SAR_VOXEL_ANIMALS_ITEMS_ATTRIBUTION,
  QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION,
  openGameArtAttribution,
  quaterniusAttribution,
} from "./attributions";

export const GLB_PRESET_FILES: GalleryPresetFile[] = [
  { file: "FishAnimated.glb", label: "Animated Fish", category: "Animated" },
  {
    file: "khronos/animated-fox.glb",
    label: "Animated Fox",
    category: "Animated",
    attribution: KHRONOS_FOX_ATTRIBUTION,
  },
  {
    file: "opengameart/animated-pliers.glb",
    label: "Animated Pliers",
    category: "Animated",
    attribution: openGameArtAttribution("LonesomeDucky", "tool-pack-2", 1452),
  },
  {
    file: "opengameart/animated-utility-knife.glb",
    label: "Animated Utility Knife",
    category: "Animated",
    attribution: openGameArtAttribution("LonesomeDucky", "tool-pack-2", 576),
  },
  { file: "AnimatedMushnub.glb", label: "Animated Mushnub", category: "Animated" },
  { file: "AnimatedSnake.glb", label: "Animated Snake", category: "Animated" },
  { file: "Bat.glb", category: "Animals" },
  { file: "Bear.glb", category: "Animals" },
  { file: "Cat.glb", category: "Animals" },
  { file: "Cheetah.glb", category: "Animals" },
  { file: "Deer.glb", category: "Animals" },
  { file: "Dinosaur.glb", category: "Animals" },
  { file: "Dog.glb", category: "Animals" },
  { file: "Dolphin.glb", category: "Animals" },
  { file: "Dragon.glb", category: "Animals" },
  { file: "Duck.glb", category: "Animals" },
  { file: "Elephant.glb", category: "Animals" },
  { file: "Fly.glb", category: "Animals" },
  { file: "Frog.glb", category: "Animals" },
  { file: "Gorilla.glb", category: "Animals" },
  { file: "Hippo.glb", category: "Animals" },
  { file: "Horse.glb", category: "Animals" },
  { file: "Koala.glb", category: "Animals" },
  { file: "Lobster.glb", category: "Animals" },
  { file: "Octopus.glb", category: "Animals" },
  { file: "Owl.glb", category: "Animals" },
  { file: "Pig.glb", category: "Animals" },
  { file: "Poodle.glb", category: "Animals" },
  { file: "Rat.glb", category: "Animals" },
  { file: "Robin.glb", category: "Animals" },
  { file: "Scorpion.glb", category: "Animals" },
  { file: "Shark.glb", category: "Animals" },
  { file: "Snail.glb", category: "Animals" },
  { file: "Wolf.glb", category: "Animals" },
  { file: "Zebra.glb", category: "Animals" },
  { file: "Bicycle.glb", category: "Vehicles" },
  { file: "Dump truck.glb", label: "Dump Truck", category: "Vehicles" },
  { file: "Policecar.glb", label: "Police Car", category: "Vehicles" },
  { file: "Taxi.glb", category: "Vehicles" },
  { file: "Truck.glb", category: "Vehicles" },
  { file: "Acousticguitar.glb", label: "Guitar (Acoustic)", category: "Instruments" },
  { file: "Electricguitar.glb", label: "Guitar (Electric)", category: "Instruments" },
  { file: "Saxophone.glb", category: "Instruments" },
  { file: "Trumpet.glb", category: "Instruments" },
  { file: "Violin.glb", category: "Instruments" },
  { file: "apple.glb", label: "Apple", category: "Food & Drink" },
  { file: "BottleChampagne.glb", label: "Champagne Bottle", category: "Food & Drink" },
  { file: "Eggplant.glb", category: "Food & Drink" },
  { file: "Grapes.glb", category: "Food & Drink" },
  { file: "Hot dog.glb", label: "Hot Dog", category: "Food & Drink" },
  { file: "Watermelon.glb", category: "Food & Drink" },
  { file: "Cactus.glb", category: "Environment" },
  { file: "Campfire.glb", category: "Environment" },
  { file: "Drill.glb", category: "Objects" },
  { file: "Globe.glb", category: "Objects" },

  // Medieval Village Pack — used by the /builder Medieval Village scene
  // preset as well as standalone models. All share the same category so
  // they group cleanly in the sidebar.
  { file: "medieval/Bag Open.glb", label: "Bag Open", category: "Medieval Village" },
  { file: "medieval/Bag.glb", category: "Medieval Village" },
  { file: "medieval/Bags.glb", category: "Medieval Village" },
  { file: "medieval/Barrel.glb", category: "Medieval Village" },
  { file: "medieval/Bell Tower.glb", label: "Bell Tower", category: "Medieval Village" },
  { file: "medieval/Bell.glb", category: "Medieval Village" },
  { file: "medieval/Bench.glb", category: "Medieval Village" },
  { file: "medieval/Bench-7uSlZo3n9Y.glb", label: "Bench (Tall)", category: "Medieval Village" },
  { file: "medieval/Blacksmith.glb", category: "Medieval Village" },
  { file: "medieval/Bonfire.glb", category: "Medieval Village" },
  { file: "medieval/Cart.glb", category: "Medieval Village" },
  { file: "medieval/Cauldron.glb", category: "Medieval Village" },
  { file: "medieval/Crate.glb", category: "Medieval Village" },
  { file: "medieval/Door Round.glb", label: "Door Round", category: "Medieval Village" },
  { file: "medieval/Door Straight.glb", label: "Door Straight", category: "Medieval Village" },
  { file: "medieval/Fantasy Barracks.glb", label: "Fantasy Barracks", category: "Medieval Village" },
  { file: "medieval/Fantasy House.glb", label: "Fantasy House", category: "Medieval Village" },
  { file: "medieval/Fantasy House-BH2XHWUNmF.glb", label: "Fantasy House (Stone)", category: "Medieval Village" },
  { file: "medieval/Fantasy House-dcPho4SUA3.glb", label: "Fantasy House (Tall)", category: "Medieval Village" },
  { file: "medieval/Fantasy Inn.glb", label: "Fantasy Inn", category: "Medieval Village" },
  { file: "medieval/Fantasy Sawmill.glb", label: "Fantasy Sawmill", category: "Medieval Village" },
  { file: "medieval/Fantasy Stable.glb", label: "Fantasy Stable", category: "Medieval Village" },
  { file: "medieval/Fence.glb", category: "Medieval Village" },
  { file: "medieval/Gazebo.glb", category: "Medieval Village" },
  { file: "medieval/Hay.glb", category: "Medieval Village" },
  { file: "medieval/Market Stand.glb", label: "Market Stand", category: "Medieval Village" },
  { file: "medieval/Market Stand-DGIM5HGISb.glb", label: "Market Stand (Variant)", category: "Medieval Village" },
  { file: "medieval/Mill.glb", category: "Medieval Village" },
  { file: "medieval/Package.glb", category: "Medieval Village" },
  { file: "medieval/Package-kYvD6QCQRd.glb", label: "Package (Small)", category: "Medieval Village" },
  { file: "medieval/Path Straight.glb", label: "Path Straight", category: "Medieval Village" },
  { file: "medieval/Rocks.glb", category: "Medieval Village" },
  { file: "medieval/Round Window.glb", label: "Round Window", category: "Medieval Village" },
  { file: "medieval/Sawmill Saw.glb", label: "Sawmill Saw", category: "Medieval Village" },
  { file: "medieval/Smoke.glb", category: "Medieval Village" },
  { file: "medieval/Stairs.glb", category: "Medieval Village" },
  { file: "medieval/Well.glb", category: "Medieval Village" },
  { file: "medieval/Window.glb", category: "Medieval Village" },
  { file: "medieval/Window-EY1zrFcme9.glb", label: "Window (Tall)", category: "Medieval Village" },

  // City Kit — used by the /builder City Block scene preset and for
  // standalone placement. 31 building variants across 6 archetypes
  // (Skyscraper, Large/Low Wide/Low/Small Building, Sign Hospital).
  { file: "city/Skyscraper.glb", category: "City Kit" },
  { file: "city/Skyscraper-BwEXdOoUSO.glb", label: "Skyscraper (A)", category: "City Kit" },
  { file: "city/Skyscraper-jIRx0AhYOR.glb", label: "Skyscraper (B)", category: "City Kit" },
  { file: "city/Skyscraper-obYD8hWLTZ.glb", label: "Skyscraper (C)", category: "City Kit" },
  { file: "city/Skyscraper-PsPe0MzK0E.glb", label: "Skyscraper (D)", category: "City Kit" },
  { file: "city/Skyscraper-XST1j6kYsL.glb", label: "Skyscraper (E)", category: "City Kit" },
  { file: "city/Large Building.glb", label: "Large Building", category: "City Kit" },
  { file: "city/Large Building-1bt4yYKmuK.glb", label: "Large Building (A)", category: "City Kit" },
  { file: "city/Large Building-3IhrYZp6tP.glb", label: "Large Building (B)", category: "City Kit" },
  { file: "city/Large Building-h7Jaq7bqMq.glb", label: "Large Building (C)", category: "City Kit" },
  { file: "city/Large Building-JgGLJH2iXj.glb", label: "Large Building (D)", category: "City Kit" },
  { file: "city/Large Building-ppwtREejXg.glb", label: "Large Building (E)", category: "City Kit" },
  { file: "city/Large Building-sxXonOmtct.glb", label: "Large Building (F)", category: "City Kit" },
  { file: "city/Low Wide.glb", label: "Low Wide", category: "City Kit" },
  { file: "city/Low Wide-DKgknsHjmr.glb", label: "Low Wide (A)", category: "City Kit" },
  { file: "city/Low Building.glb", label: "Low Building", category: "City Kit" },
  { file: "city/Low Building-4RoPd9BkSx.glb", label: "Low Building (A)", category: "City Kit" },
  { file: "city/Low Building-9fEKMpTsAi.glb", label: "Low Building (B)", category: "City Kit" },
  { file: "city/Low Building-AXFdNPAEc9.glb", label: "Low Building (C)", category: "City Kit" },
  { file: "city/Low Building-dYEbYdPfJr.glb", label: "Low Building (D)", category: "City Kit" },
  { file: "city/Low Building-sObKC8Mio2.glb", label: "Low Building (E)", category: "City Kit" },
  { file: "city/Low Building-tuieC1Pj0a.glb", label: "Low Building (F)", category: "City Kit" },
  { file: "city/Low Building-XsFOzw8E5N.glb", label: "Low Building (G)", category: "City Kit" },
  { file: "city/Low Building-zfjlejAxB7.glb", label: "Low Building (H)", category: "City Kit" },
  { file: "city/Small Building.glb", label: "Small Building", category: "City Kit" },
  { file: "city/Small Building-gyjF60t7CG.glb", label: "Small Building (A)", category: "City Kit" },
  { file: "city/Small Building-QjL4Fo9dU9.glb", label: "Small Building (B)", category: "City Kit" },
  { file: "city/Small Building-Rq572hdKEz.glb", label: "Small Building (C)", category: "City Kit" },
  { file: "city/Small Building-t9j9Lof5ul.glb", label: "Small Building (D)", category: "City Kit" },
  { file: "city/Small Building-yLvnMqC9ZG.glb", label: "Small Building (E)", category: "City Kit" },
  { file: "city/Sign Hospital.glb", label: "Sign Hospital", category: "City Kit" },

  // Urban Pack — buildings + cars + street furniture + a few characters.
  // Used by the /builder "City Street" scene plus ad-hoc placement.
  { file: "urban/Big Building.glb", label: "Big Building", category: "Urban Pack" },
  { file: "urban/Brown Building.glb", label: "Brown Building", category: "Urban Pack" },
  { file: "urban/Building Green.glb", label: "Building (Green)", category: "Urban Pack" },
  { file: "urban/Building Red.glb", label: "Building (Red)", category: "Urban Pack" },
  { file: "urban/Building Red Corner.glb", label: "Building (Red Corner)", category: "Urban Pack" },
  { file: "urban/Greenhouse.glb", category: "Urban Pack" },
  { file: "urban/Pizza Corner.glb", label: "Pizza Corner", category: "Urban Pack" },

  { file: "urban/Road Bits.glb", label: "Road", category: "Urban Pack" },
  { file: "urban/Floor Hole.glb", label: "Floor Hole", category: "Urban Pack" },
  { file: "urban/Manhole Cover.glb", label: "Manhole Cover", category: "Urban Pack" },

  { file: "urban/Car.glb", category: "Urban Pack" },
  { file: "urban/Car-unqqkULtRU.glb", label: "Car (Variant)", category: "Urban Pack" },
  { file: "urban/SUV.glb", category: "Urban Pack" },
  { file: "urban/Van.glb", category: "Urban Pack" },
  { file: "urban/Pickup Truck.glb", label: "Pickup Truck", category: "Urban Pack" },
  { file: "urban/Bus.glb", category: "Urban Pack" },
  { file: "urban/Sports Car.glb", label: "Sports Car", category: "Urban Pack" },
  { file: "urban/Sports Car-Gzj704DXdr.glb", label: "Sports Car (Variant)", category: "Urban Pack" },
  { file: "urban/Police Car.glb", label: "Police Car", category: "Urban Pack" },
  { file: "urban/Motorcycle.glb", category: "Urban Pack" },
  { file: "urban/Bicycle.glb", category: "Urban Pack" },

  { file: "urban/Bus Stop.glb", label: "Bus Stop", category: "Urban Pack" },
  { file: "urban/Bus stop sign.glb", label: "Bus Stop Sign", category: "Urban Pack" },
  { file: "urban/Stop sign.glb", label: "Stop Sign", category: "Urban Pack" },
  { file: "urban/Traffic Light.glb", label: "Traffic Light", category: "Urban Pack" },
  { file: "urban/Billboard.glb", category: "Urban Pack" },
  { file: "urban/Rock band poster.glb", label: "Poster", category: "Urban Pack" },

  { file: "urban/Bench.glb", category: "Urban Pack" },
  { file: "urban/Trash Can.glb", label: "Trash Can", category: "Urban Pack" },
  { file: "urban/trah bag grey.glb", label: "Trash Bag", category: "Urban Pack" },
  { file: "urban/Dumpster.glb", category: "Urban Pack" },
  { file: "urban/Mailbox.glb", category: "Urban Pack" },
  { file: "urban/Fire hydrant.glb", label: "Fire Hydrant", category: "Urban Pack" },
  { file: "urban/Cone.glb", label: "Traffic Cone", category: "Urban Pack" },
  { file: "urban/Box.glb", category: "Urban Pack" },
  { file: "urban/Power Box.glb", label: "Power Box", category: "Urban Pack" },
  { file: "urban/Air conditioner.glb", label: "Air Conditioner", category: "Urban Pack" },
  { file: "urban/ATM.glb", category: "Urban Pack" },
  { file: "urban/Tree.glb", category: "Urban Pack" },
  { file: "urban/Planter & Bushes.glb", label: "Planter & Bushes", category: "Urban Pack" },
  { file: "urban/Flower Pot.glb", label: "Flower Pot", category: "Urban Pack" },
  { file: "urban/Flower Pot-Kgt363WkKd.glb", label: "Flower Pot (Variant)", category: "Urban Pack" },
  { file: "urban/Fence.glb", category: "Urban Pack" },
  { file: "urban/Fence Piece.glb", label: "Fence Piece", category: "Urban Pack" },
  { file: "urban/Fence End.glb", label: "Fence End", category: "Urban Pack" },
  { file: "urban/Fire Exit.glb", label: "Fire Exit", category: "Urban Pack" },
  { file: "urban/Roof Exit.glb", label: "Roof Exit", category: "Urban Pack" },
  { file: "urban/Washing Line.glb", label: "Washing Line", category: "Urban Pack" },
  { file: "urban/Debris Papers.glb", label: "Debris", category: "Urban Pack" },

  { file: "urban/Man.glb", category: "Urban Pack" },
  { file: "urban/Adventurer.glb", category: "Urban Pack" },
  { file: "urban/Animated Woman.glb", label: "Animated Woman", category: "Urban Pack" },
  { file: "urban/Animated Woman-nIItLV9nxS.glb", label: "Animated Woman (A)", category: "Urban Pack" },
  { file: "urban/Animated Woman-qJ2gsTUBHL.glb", label: "Animated Woman (B)", category: "Urban Pack" },
];

export const POLY_PIZZA_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "poly-pizza/fruit-crate.glb",
    label: "Fruit Crate",
    category: "Food & Drink",
    attribution: {
      creator: "BlenderVoyage",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/aXulVWHOeV",
      tris: 196,
    },
  },
  {
    file: "poly-pizza/pizza-slice.glb",
    label: "Pizza Slice",
    category: "Food & Drink",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/CA4HtaaMJn",
      tris: 392,
    },
  },
  {
    file: "poly-pizza/sheep.glb",
    label: "Sheep",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/C39AUXUUes",
      tris: 610,
    },
  },
  {
    file: "poly-pizza/large-building.glb",
    label: "Large Building",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/yKo7F36Qk2",
      tris: 950,
    },
  },
  {
    file: "poly-pizza/animated-robot.glb",
    label: "Animated Robot",
    category: "Animated",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/QCm7qe9uNJ",
      tris: 1425,
    },
  },
  {
    file: "poly-pizza/bird.glb",
    label: "Bird",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/gYYC0gYMnw",
      tris: 1204,
    },
  },
  {
    file: "poly-pizza/cow.glb",
    label: "Cow",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/5XSc2Fka3F",
      tris: 796,
    },
  },
  {
    file: "poly-pizza/ducky.glb",
    label: "Ducky",
    category: "Animals",
    attribution: {
      creator: "Isa Lousberg",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/gt2eYOyOvU",
      tris: 604,
    },
  },
  {
    file: "poly-pizza/fish.glb",
    label: "Fish",
    category: "Animals",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/HkUAXudvBt",
      tris: 233,
    },
  },
  {
    file: "poly-pizza/llama.glb",
    label: "Llama",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/JxVJ9rfWGy",
      tris: 661,
    },
  },
  {
    file: "poly-pizza/pug.glb",
    label: "Pug",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/1gXKv15ik8",
      tris: 644,
    },
  },
  {
    file: "poly-pizza/guard-tower.glb",
    label: "Guard Tower",
    category: "Architecture",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/sbaM8I229r",
      tris: 344,
    },
  },
  {
    file: "poly-pizza/house.glb",
    label: "House",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/7VSVwAg2T3",
      tris: 381,
    },
  },
  {
    file: "poly-pizza/skyscraper.glb",
    label: "Skyscraper",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/XST1j6kYsL",
      tris: 456,
    },
  },
  {
    file: "poly-pizza/tower.glb",
    label: "Tower",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/5lvG0WtuTU",
      tris: 683,
    },
  },
  {
    file: "poly-pizza/two-story-house.glb",
    label: "Two story house",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/sGgL4Nt7I7",
      tris: 630,
    },
  },
  {
    file: "poly-pizza/watch-tower.glb",
    label: "Watch Tower",
    category: "Architecture",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/f2J0aSLVi4",
      tris: 656,
    },
  },
  {
    file: "poly-pizza/bucket.glb",
    label: "Bucket",
    category: "Objects",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/tKTttwROq7",
      tris: 532,
    },
  },
  {
    file: "poly-pizza/can.glb",
    label: "Can",
    category: "Objects",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/YnowJvWqxE",
      tris: 428,
    },
  },
  {
    file: "poly-pizza/bread.glb",
    label: "Bread",
    category: "Food & Drink",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/luo9BHRaax",
      tris: 116,
    },
  },
  {
    file: "poly-pizza/cup-tea.glb",
    label: "Cup Tea",
    category: "Food & Drink",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/FUSyrlibw0",
      tris: 108,
    },
  },
  {
    file: "poly-pizza/egg-fried.glb",
    label: "Egg Fried",
    category: "Food & Drink",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/NVrB2yd66v",
      tris: 101,
    },
  },
  {
    file: "poly-pizza/rock.glb",
    label: "Rock",
    category: "Environment",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/cBqdRdLDDL",
      tris: 120,
    },
  },
  {
    file: "poly-pizza/rock-medium.glb",
    label: "Rock Medium",
    category: "Environment",
    galleryBucket: "Textured",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/s1OJ3bBzqc",
      tris: 342,
    },
  },
  {
    file: "poly-pizza/box.glb",
    label: "Box",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: {
      creator: "Kay Lousberg",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/ykZ23x9d6p",
      tris: 32,
    },
  },
  {
    file: "poly-pizza/empty-box.glb",
    label: "Empty Box",
    category: "Objects",
    attribution: {
      creator: "CreativeTrio",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/pZBpmjtvw8",
      tris: 76,
    },
  },
  {
    file: "poly-pizza/animated-human.glb",
    label: "Animated Human",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/c3Ibh9I3udk",
      tris: 1578,
    },
  },
  {
    file: "poly-pizza/character-animated.glb",
    label: "Character Animated",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/DgOCW9ZCRJ",
      tris: 1246,
    },
  },
  {
    file: "poly-pizza/human-dude-guy.glb",
    label: "Human Dude Guy",
    category: "Characters",
    attribution: {
      creator: "hat_my_guy",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/83DpVkzvWk",
      tris: 1151,
    },
  },
  {
    file: "poly-pizza/man.glb",
    label: "Man",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/HMnuH5geEG",
      tris: 1216,
    },
  },
  {
    file: "poly-pizza/rabbit-blond.glb",
    label: "Rabbit Blond",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/cMsI6FDhNx",
      tris: 1570,
    },
  },
  {
    file: "poly-pizza/arrow.glb",
    label: "Arrow",
    category: "Weapons",
    attribution: {
      creator: "CreativeTrio",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/dZVjrxZdaB",
      tris: 119,
    },
  },
  {
    file: "poly-pizza/sword.glb",
    label: "Sword",
    category: "Weapons",
    attribution: {
      creator: "hat_my_guy",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/FvUHJZzy1M",
      tris: 141,
    },
  },
];

export const VOX_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "AncientCrashSite.vox",
    label: "Ancient Crash Site",
    category: "VOX",
    targetSize: 70,
    zoom: 0.35,
    attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION,
  },
  { file: "army.vox", label: "Army", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "desert.vox", label: "Desert", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "desert2.vox", label: "Desert 2", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "Garden.vox", category: "VOX", attribution: MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION },
  { file: "Building03.vox", label: "Building 03", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "HUT.vox", label: "Hut", category: "VOX", attribution: MONOGON_COUNTRY_SIDE_ATTRIBUTION },
  { file: "house.vox", label: "House", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "pyramid.vox", label: "Pyramid", category: "VOX", attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION },
  { file: "skyscraper.vox", label: "Skyscraper", category: "VOX", attribution: MONOGON_CYBERPUNK_CITY_ATTRIBUTION },
  { file: "stairs.vox", label: "Stairs", category: "VOX", attribution: MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION },
  { file: "Plane_03.vox", label: "Plane 03", category: "VOX", attribution: MONOGON_VOXEL_PLANE_ATTRIBUTION },
  { file: "bus.vox", label: "Bus", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "tank.vox", label: "Tank", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "arachnoid.vox", label: "Arachnoid", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "MechaGolem.vox", label: "Mecha Golem", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "mecha.vox", label: "Mecha", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "StarMarineTrooper.vox", label: "Star Marine Trooper", category: "VOX", attribution: MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION },
  { file: "apple.vox", label: "Apple", category: "VOX", attribution: SONA_SAR_VOXEL_ANIMALS_ITEMS_ATTRIBUTION },
  { file: "dual.vox", label: "Dual", category: "VOX", attribution: MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION },
  { file: "Treasure.vox", category: "VOX", attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION },
  { file: "tree.vox", label: "Tree", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
];

const ULTIMATE_SPACESHIPS_ROOT = "quaternius/ultimate-spaceships";

export function ultimateSpaceshipPreset(
  slug: string,
  name: string,
  texture: string,
  tris: number,
): ObjGalleryPresetFile {
  return {
    file: `${ULTIMATE_SPACESHIPS_ROOT}/${slug}/${name}.obj`,
    label: `Ship - ${name}`,
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.24,
    attribution: { ...QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION, tris },
    options: {
      materialTextures: {
        Texture: `/gallery/obj/${ULTIMATE_SPACESHIPS_ROOT}/${slug}/${texture}`,
      },
    },
  };
}

export const OBJ_PRESET_FILES: ObjGalleryPresetFile[] = [
  {
    file: "opengameart/crate/Box.obj",
    label: "Crate",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("Kutejnikov", "crate-5", 12),
  },
  {
    file: "opengameart/hay-bale/hay_bale.obj",
    label: "Hay Bale",
    category: "Environment",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("Mish7913", "hay-bale-0", 108),
  },
  {
    file: "opengameart/low-poly-car/car.obj",
    label: "Low Poly Car",
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.3,
    attribution: openGameArtAttribution("drummyfish", "low-poly-car-3", 228),
  },
  {
    file: "opengameart/wood-crate/woodcrate.obj",
    label: "Wood Crate",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("GGBotNet", "wood-crate-3d", 284),
  },
  {
    file: "opengameart/broken-stone-slab/stone.obj",
    label: "Broken Stone Slab",
    category: "Environment",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("Kutejnikov", "broken-stone-slab", 186),
  },
  {
    file: "opengameart/frog-guy/frog.obj",
    label: "Frog Guy",
    category: "Characters",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("drummyfish", "frog-guy", 356),
  },
  {
    file: "opengameart/game-cartridge/cartridge.obj",
    label: "Game Cartridge",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("Kutejnikov", "game-cartridge", 432, "CC-BY 4.0"),
  },
  {
    file: "opengameart/fire-extinguisher/extinguisher.obj",
    label: "Fire Extinguisher",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("cron", "fire-extinguisher-2", 818, "CC-BY-SA 4.0"),
  },
  {
    file: "opengameart/keycard/keycard.obj",
    label: "Keycard",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("codeinfernogames", "3d-keycard", 20),
  },
  {
    file: "opengameart/pirate-coin/pirate-coin.obj",
    label: "Pirate Coin",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("acasas", "3d-pirate-coin", 624, "CC-BY 3.0"),
  },
  {
    file: "opengameart/perfume-bottle/perfume.obj",
    label: "Perfume Bottle",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("PantherOne", "perfume-bottle-persian", 196, "CC-BY 3.0"),
  },
  {
    file: "opengameart/grandfather-clock/grandfather-clock.obj",
    label: "Grandfather Clock",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("GGBotNet", "grandfather-clock-3d", 106, "CC-BY 4.0"),
  },
  {
    file: "opengameart/old-book/old-book.obj",
    label: "Old Book",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("GGBotNet", "old-bible-3d", 60, "CC-BY 4.0"),
  },
  {
    file: "opengameart/haunted-house/hauntedhouse.obj",
    label: "Haunted House",
    category: "Buildings",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("naovia", "haunted-house", 377),
  },
  {
    file: "opengameart/biplane/biplane.obj",
    label: "Low Poly Biplane",
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.25,
    attribution: openGameArtAttribution("mfep", "low-poly-biplane", 668),
  },
  ultimateSpaceshipPreset("challenger", "Challenger", "Challenger_Green.png", 1748),
  ultimateSpaceshipPreset("executioner", "Executioner", "Executioner_Blue.png", 3388),
  ultimateSpaceshipPreset("omen", "Omen", "Omen_Orange.png", 1426),
  ultimateSpaceshipPreset("pancake", "Pancake", "Pancake_Orange.png", 2688),
  ultimateSpaceshipPreset("spitfire", "Spitfire", "Spitfire_Red.png", 3512),
  ultimateSpaceshipPreset("zenith", "Zenith", "Zenith_Red.png", 2152),
  {
    file: "quaternius/nature/Lilypad.obj",
    label: "Lilypad",
    category: "Environment",
    zoom: 0.45,
    attribution: quaterniusAttribution("https://quaternius.com/packs/ultimatenature.html", 372),
  },
  {
    file: "quaternius/dungeon/Chest_gold.obj",
    label: "Treasure Chest",
    category: "Objects",
    zoom: 0.4,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 436),
  },
  {
    file: "quaternius/dungeon/Torch.obj",
    label: "Torch",
    category: "Objects",
    zoom: 0.35,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 518),
  },
  {
    file: "quaternius/dungeon/Candelabrum.obj",
    label: "Candelabrum",
    category: "Objects",
    zoom: 0.35,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 636),
  },
];
