import type { GalleryPresetFile, ObjGalleryPresetFile } from "../types";
import {
  KHRONOS_FOX_ATTRIBUTION,
  MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION,
  MINI_MIKES_METRO_MINIS_ATTRIBUTION,
  MONOGON_DESERT_TOWN_ATTRIBUTION,
  MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION,
  MONOGON_COUNTRY_SIDE_ATTRIBUTION,
  MONOGON_CYBERPUNK_CITY_ATTRIBUTION,
  MONOGON_VOXEL_PLANE_ATTRIBUTION,
  MONOGON_VOXEL_MECHAS_ATTRIBUTION,
  MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION,
  SONA_SAR_VOXEL_ANIMALS_ITEMS_ATTRIBUTION,
  QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION,
  openGameArtAttribution,
  quaterniusAttribution,
} from "./attributions";

export const GLB_PRESET_FILES: GalleryPresetFile[] = [
  { file: "FishAnimated.glb", label: "Animated Fish", category: "Animated" },
  {
    file: "khronos/animated-fox.glb",
    label: "Animated Fox",
    category: "Animated",
    attribution: KHRONOS_FOX_ATTRIBUTION,
  },
  {
    file: "opengameart/animated-pliers.glb",
    label: "Animated Pliers",
    category: "Animated",
    attribution: openGameArtAttribution("LonesomeDucky", "tool-pack-2", 1452),
  },
  {
    file: "opengameart/animated-utility-knife.glb",
    label: "Animated Utility Knife",
    category: "Animated",
    attribution: openGameArtAttribution("LonesomeDucky", "tool-pack-2", 576),
  },
  { file: "AnimatedMushnub.glb", label: "Animated Mushnub", category: "Animated" },
  { file: "AnimatedSnake.glb", label: "Animated Snake", category: "Animated" },
  { file: "Bat.glb", category: "Animals" },
  { file: "Bear.glb", category: "Animals" },
  { file: "Cat.glb", category: "Animals" },
  { file: "Cheetah.glb", category: "Animals" },
  { file: "Deer.glb", category: "Animals" },
  { file: "Dinosaur.glb", category: "Animals" },
  { file: "Dog.glb", category: "Animals" },
  { file: "Dolphin.glb", category: "Animals" },
  { file: "Dragon.glb", category: "Animals" },
  { file: "Duck.glb", category: "Animals" },
  { file: "Elephant.glb", category: "Animals" },
  { file: "Fly.glb", category: "Animals" },
  { file: "Frog.glb", category: "Animals" },
  { file: "Gorilla.glb", category: "Animals" },
  { file: "Hippo.glb", category: "Animals" },
  { file: "Horse.glb", category: "Animals" },
  { file: "Koala.glb", category: "Animals" },
  { file: "Lobster.glb", category: "Animals" },
  { file: "Octopus.glb", category: "Animals" },
  { file: "Owl.glb", category: "Animals" },
  { file: "Pig.glb", category: "Animals" },
  { file: "Poodle.glb", category: "Animals" },
  { file: "Rat.glb", category: "Animals" },
  { file: "Robin.glb", category: "Animals" },
  { file: "Scorpion.glb", category: "Animals" },
  { file: "Shark.glb", category: "Animals" },
  { file: "Snail.glb", category: "Animals" },
  { file: "Wolf.glb", category: "Animals" },
  { file: "Zebra.glb", category: "Animals" },
  { file: "Bicycle.glb", category: "Vehicles" },
  { file: "Dump truck.glb", label: "Dump Truck", category: "Vehicles" },
  { file: "Policecar.glb", label: "Police Car", category: "Vehicles" },
  { file: "Taxi.glb", category: "Vehicles" },
  { file: "Truck.glb", category: "Vehicles" },
  { file: "Acousticguitar.glb", label: "Guitar (Acoustic)", category: "Instruments" },
  { file: "Electricguitar.glb", label: "Guitar (Electric)", category: "Instruments" },
  { file: "Saxophone.glb", category: "Instruments" },
  { file: "Trumpet.glb", category: "Instruments" },
  { file: "Violin.glb", category: "Instruments" },
  { file: "apple.glb", label: "Apple", category: "Food & Drink" },
  { file: "BottleChampagne.glb", label: "Champagne Bottle", category: "Food & Drink" },
  { file: "Eggplant.glb", category: "Food & Drink" },
  { file: "Grapes.glb", category: "Food & Drink" },
  { file: "Hot dog.glb", label: "Hot Dog", category: "Food & Drink" },
  { file: "Watermelon.glb", category: "Food & Drink" },
  { file: "Cactus.glb", category: "Environment" },
  { file: "Campfire.glb", category: "Environment" },
  { file: "Drill.glb", category: "Objects" },
  { file: "Globe.glb", category: "Objects" },
];

export const POLY_PIZZA_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "poly-pizza/fruit-crate.glb",
    label: "Fruit Crate",
    category: "Food & Drink",
    attribution: {
      creator: "BlenderVoyage",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/aXulVWHOeV",
      tris: 196,
    },
  },
  {
    file: "poly-pizza/pizza-slice.glb",
    label: "Pizza Slice",
    category: "Food & Drink",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/CA4HtaaMJn",
      tris: 392,
    },
  },
  {
    file: "poly-pizza/sheep.glb",
    label: "Sheep",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/C39AUXUUes",
      tris: 610,
    },
  },
  {
    file: "poly-pizza/large-building.glb",
    label: "Large Building",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/yKo7F36Qk2",
      tris: 950,
    },
  },
  {
    file: "poly-pizza/animated-robot.glb",
    label: "Animated Robot",
    category: "Animated",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/QCm7qe9uNJ",
      tris: 1425,
    },
  },
  {
    file: "poly-pizza/bird.glb",
    label: "Bird",
    category: "Animals",
    galleryBucket: "Textured",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/gYYC0gYMnw",
      tris: 1204,
    },
  },
  {
    file: "poly-pizza/cow.glb",
    label: "Cow",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/5XSc2Fka3F",
      tris: 796,
    },
  },
  {
    file: "poly-pizza/ducky.glb",
    label: "Ducky",
    category: "Animals",
    galleryBucket: "Textured",
    attribution: {
      creator: "Isa Lousberg",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/gt2eYOyOvU",
      tris: 604,
    },
  },
  {
    file: "poly-pizza/fish.glb",
    label: "Fish",
    category: "Animals",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/HkUAXudvBt",
      tris: 233,
    },
  },
  {
    file: "poly-pizza/llama.glb",
    label: "Llama",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/JxVJ9rfWGy",
      tris: 661,
    },
  },
  {
    file: "poly-pizza/pug.glb",
    label: "Pug",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/1gXKv15ik8",
      tris: 644,
    },
  },
  {
    file: "poly-pizza/guard-tower.glb",
    label: "Guard Tower",
    category: "Architecture",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/sbaM8I229r",
      tris: 344,
    },
  },
  {
    file: "poly-pizza/house.glb",
    label: "House",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/7VSVwAg2T3",
      tris: 381,
    },
  },
  {
    file: "poly-pizza/skyscraper.glb",
    label: "Skyscraper",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/XST1j6kYsL",
      tris: 456,
    },
  },
  {
    file: "poly-pizza/tower.glb",
    label: "Tower",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/5lvG0WtuTU",
      tris: 683,
    },
  },
  {
    file: "poly-pizza/two-story-house.glb",
    label: "Two story house",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/sGgL4Nt7I7",
      tris: 630,
    },
  },
  {
    file: "poly-pizza/watch-tower.glb",
    label: "Watch Tower",
    category: "Architecture",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/f2J0aSLVi4",
      tris: 656,
    },
  },
  {
    file: "poly-pizza/bucket.glb",
    label: "Bucket",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/tKTttwROq7",
      tris: 532,
    },
  },
  {
    file: "poly-pizza/can.glb",
    label: "Can",
    category: "Objects",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/YnowJvWqxE",
      tris: 428,
    },
  },
  {
    file: "poly-pizza/bread.glb",
    label: "Bread",
    category: "Food & Drink",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/luo9BHRaax",
      tris: 116,
    },
  },
  {
    file: "poly-pizza/cup-tea.glb",
    label: "Cup Tea",
    category: "Food & Drink",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/FUSyrlibw0",
      tris: 108,
    },
  },
  {
    file: "poly-pizza/egg-fried.glb",
    label: "Egg Fried",
    category: "Food & Drink",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/NVrB2yd66v",
      tris: 101,
    },
  },
  {
    file: "poly-pizza/rock.glb",
    label: "Rock",
    category: "Environment",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/cBqdRdLDDL",
      tris: 120,
    },
  },
  {
    file: "poly-pizza/rock-medium.glb",
    label: "Rock Medium",
    category: "Environment",
    galleryBucket: "Textured",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/s1OJ3bBzqc",
      tris: 342,
    },
  },
  {
    file: "poly-pizza/box.glb",
    label: "Box",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: {
      creator: "Kay Lousberg",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/ykZ23x9d6p",
      tris: 32,
    },
  },
  {
    file: "poly-pizza/empty-box.glb",
    label: "Empty Box",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: {
      creator: "CreativeTrio",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/pZBpmjtvw8",
      tris: 76,
    },
  },
  {
    file: "poly-pizza/animated-human.glb",
    label: "Animated Human",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/c3Ibh9I3udk",
      tris: 1578,
    },
  },
  {
    file: "poly-pizza/character-animated.glb",
    label: "Character Animated",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/DgOCW9ZCRJ",
      tris: 1246,
    },
  },
  {
    file: "poly-pizza/human-dude-guy.glb",
    label: "Human Dude Guy",
    category: "Characters",
    attribution: {
      creator: "hat_my_guy",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/83DpVkzvWk",
      tris: 1151,
    },
  },
  {
    file: "poly-pizza/man.glb",
    label: "Man",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/HMnuH5geEG",
      tris: 1216,
    },
  },
  {
    file: "poly-pizza/rabbit-blond.glb",
    label: "Rabbit Blond",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/cMsI6FDhNx",
      tris: 1570,
    },
  },
  {
    file: "poly-pizza/arrow.glb",
    label: "Arrow",
    category: "Weapons",
    galleryBucket: "Textured",
    attribution: {
      creator: "CreativeTrio",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/dZVjrxZdaB",
      tris: 119,
    },
  },
  {
    file: "poly-pizza/sword.glb",
    label: "Sword",
    category: "Weapons",
    attribution: {
      creator: "hat_my_guy",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/FvUHJZzy1M",
      tris: 141,
    },
  },
];

export const VOX_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "AncientCrashSite.vox",
    label: "Ancient Crash Site",
    category: "VOX",
    targetSize: 70,
    zoom: 0.35,
    attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION,
  },
  { file: "army.vox", label: "Army", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "desert.vox", label: "Desert", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "desert2.vox", label: "Desert 2", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "Garden.vox", category: "VOX", attribution: MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION },
  { file: "Building03.vox", label: "Building 03", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "HUT.vox", label: "Hut", category: "VOX", attribution: MONOGON_COUNTRY_SIDE_ATTRIBUTION },
  { file: "house.vox", label: "House", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "pyramid.vox", label: "Pyramid", category: "VOX", attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION },
  { file: "skyscraper.vox", label: "Skyscraper", category: "VOX", attribution: MONOGON_CYBERPUNK_CITY_ATTRIBUTION },
  { file: "stairs.vox", label: "Stairs", category: "VOX", attribution: MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION },
  { file: "Plane_03.vox", label: "Plane 03", category: "VOX", attribution: MONOGON_VOXEL_PLANE_ATTRIBUTION },
  { file: "bus.vox", label: "Bus", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "tank.vox", label: "Tank", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "arachnoid.vox", label: "Arachnoid", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "MechaGolem.vox", label: "Mecha Golem", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "mecha.vox", label: "Mecha", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "StarMarineTrooper.vox", label: "Star Marine Trooper", category: "VOX", attribution: MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION },
  { file: "apple.vox", label: "Apple", category: "VOX", attribution: SONA_SAR_VOXEL_ANIMALS_ITEMS_ATTRIBUTION },
  { file: "dual.vox", label: "Dual", category: "VOX", attribution: MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION },
  { file: "Treasure.vox", category: "VOX", attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION },
  { file: "tree.vox", label: "Tree", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
];

const ULTIMATE_SPACESHIPS_ROOT = "quaternius/ultimate-spaceships";

export function ultimateSpaceshipPreset(
  slug: string,
  name: string,
  texture: string,
  tris: number,
): ObjGalleryPresetFile {
  return {
    file: `${ULTIMATE_SPACESHIPS_ROOT}/${slug}/${name}.obj`,
    label: `Ship - ${name}`,
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.24,
    attribution: { ...QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION, tris },
    options: {
      materialTextures: {
        Texture: `/gallery/obj/${ULTIMATE_SPACESHIPS_ROOT}/${slug}/${texture}`,
      },
    },
  };
}

export const OBJ_PRESET_FILES: ObjGalleryPresetFile[] = [
  {
    file: "opengameart/crate/Box.obj",
    label: "Crate",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("Kutejnikov", "crate-5", 12),
  },
  {
    file: "opengameart/hay-bale/hay_bale.obj",
    label: "Hay Bale",
    category: "Environment",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("Mish7913", "hay-bale-0", 108),
  },
  {
    file: "opengameart/low-poly-car/car.obj",
    label: "Low Poly Car",
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.3,
    attribution: openGameArtAttribution("drummyfish", "low-poly-car-3", 228),
  },
  {
    file: "opengameart/wood-crate/woodcrate.obj",
    label: "Wood Crate",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("GGBotNet", "wood-crate-3d", 284),
  },
  {
    file: "opengameart/broken-stone-slab/stone.obj",
    label: "Broken Stone Slab",
    category: "Environment",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("Kutejnikov", "broken-stone-slab", 186),
  },
  {
    file: "opengameart/frog-guy/frog.obj",
    label: "Frog Guy",
    category: "Characters",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("drummyfish", "frog-guy", 356),
  },
  {
    file: "opengameart/game-cartridge/cartridge.obj",
    label: "Game Cartridge",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("Kutejnikov", "game-cartridge", 432, "CC-BY 4.0"),
  },
  {
    file: "opengameart/fire-extinguisher/extinguisher.obj",
    label: "Fire Extinguisher",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("cron", "fire-extinguisher-2", 818, "CC-BY-SA 4.0"),
  },
  {
    file: "opengameart/keycard/keycard.obj",
    label: "Keycard",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("codeinfernogames", "3d-keycard", 20),
  },
  {
    file: "opengameart/pirate-coin/pirate-coin.obj",
    label: "Pirate Coin",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("acasas", "3d-pirate-coin", 624, "CC-BY 3.0"),
  },
  {
    file: "opengameart/perfume-bottle/perfume.obj",
    label: "Perfume Bottle",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("PantherOne", "perfume-bottle-persian", 196, "CC-BY 3.0"),
  },
  {
    file: "opengameart/grandfather-clock/grandfather-clock.obj",
    label: "Grandfather Clock",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("GGBotNet", "grandfather-clock-3d", 106, "CC-BY 4.0"),
  },
  {
    file: "opengameart/old-book/old-book.obj",
    label: "Old Book",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("GGBotNet", "old-bible-3d", 60, "CC-BY 4.0"),
  },
  {
    file: "opengameart/haunted-house/hauntedhouse.obj",
    label: "Haunted House",
    category: "Buildings",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("naovia", "haunted-house", 377),
  },
  {
    file: "opengameart/biplane/biplane.obj",
    label: "Low Poly Biplane",
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.25,
    attribution: openGameArtAttribution("mfep", "low-poly-biplane", 668),
  },
  ultimateSpaceshipPreset("challenger", "Challenger", "Challenger_Green.png", 1748),
  ultimateSpaceshipPreset("executioner", "Executioner", "Executioner_Blue.png", 3388),
  ultimateSpaceshipPreset("omen", "Omen", "Omen_Orange.png", 1426),
  ultimateSpaceshipPreset("pancake", "Pancake", "Pancake_Orange.png", 2688),
  ultimateSpaceshipPreset("spitfire", "Spitfire", "Spitfire_Red.png", 3512),
  ultimateSpaceshipPreset("zenith", "Zenith", "Zenith_Red.png", 2152),
  {
    file: "quaternius/nature/Lilypad.obj",
    label: "Lilypad",
    category: "Environment",
    zoom: 0.45,
    attribution: quaterniusAttribution("https://quaternius.com/packs/ultimatenature.html", 372),
  },
  {
    file: "quaternius/dungeon/Chest_gold.obj",
    label: "Treasure Chest",
    category: "Objects",
    zoom: 0.4,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 436),
  },
  {
    file: "quaternius/dungeon/Torch.obj",
    label: "Torch",
    category: "Objects",
    zoom: 0.35,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 518),
  },
  {
    file: "quaternius/dungeon/Candelabrum.obj",
    label: "Candelabrum",
    category: "Objects",
    zoom: 0.35,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 636),
  },
];
