import type { PresetModel, PrimitivePreset } from "../types";
import {
  GOOGLE_POLY_AMBER_ATTRIBUTION,
  KANGAROOZ_STING_ATTRIBUTION,
  PROJECT_CHRONO_OFFROAD_ATTRIBUTION,
  QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION,
  ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  GOOGLE_POLY_FLYING_SAUCER_ATTRIBUTION,
  UTAH_TEAPOT_ATTRIBUTION,
  KENNEY_MINIGOLF_ATTRIBUTION,
  PRIMITIVE_ATTRIBUTION,
} from "./attributions";
import { GLB_PRESET_FILES, POLY_PIZZA_PRESET_FILES, VOX_PRESET_FILES, OBJ_PRESET_FILES, STL_PRESET_FILES } from "./presetFiles";
import { glbPreset, objPreset, stlPreset, voxPreset } from "./presetBuilders";
import { resolveGeometry } from "@glyphcss/core";
import type { GlyphGeometryName, Polygon, Vec3 } from "@glyphcss/core";

/**
 * Rotate polygons +90° around the world X axis so their natural Y-up axis maps
 * to the screen-up direction. Glyphcss inherits asciss's Z-up screen convention
 * — at default camera rotation (rotX 65°, rotY 45°), world +Z appears at the
 * top of the viewport and world +Y appears to the right. The axially-symmetric
 * helpers (cone, cylinder, pyramid, prism, antiprism, bipyramid, trapezohedron)
 * all build along +Y, so without this transform the cone would lie on its
 * side. Maps `(x, y, z) → (x, -z, y)`.
 */
function uprightAlongZ(polygons: Polygon[]): Polygon[] {
  return polygons.map((poly) => ({
    ...poly,
    vertices: poly.vertices.map(([x, y, z]) => [x, -z, y] as Vec3),
  }));
}

const PRIMITIVE_DEFAULTS = {
  kind: "primitive" as const,
  category: "Primitives",
  galleryBucket: "Primitives" as const,
  attribution: PRIMITIVE_ATTRIBUTION,
  // rotX / rotY are in DEGREES — camera accepts degrees. Default (65°, 45°)
  // is the classic isometric view. zoom is px/world-unit (BASE_TILE=50).
  zoom: 0.05,
  rotX: 65,
  rotY: 45,
};

const PRIMITIVE_GEOMETRY_SIZE: Partial<Record<GlyphGeometryName, number>> = {
  cube: 100,
  sphere: 50,
  tetrahedron: 80,
  octahedron: 70,
  dodecahedron: 80,
  icosahedron: 80,
  cylinder: 50,
  cone: 50,
  torus: 50,
  pyramid: 50,
  prism: 50,
  antiprism: 50,
  bipyramid: 50,
  trapezohedron: 50,
};

export function primitiveGeometrySize(name: string): number {
  return PRIMITIVE_GEOMETRY_SIZE[name as GlyphGeometryName] ?? 80;
}

function primitiveGeometry(name: GlyphGeometryName): Polygon[] {
  return resolveGeometry(name, { size: primitiveGeometrySize(name) });
}

const PRIMITIVE_PRESETS: PrimitivePreset[] = [
  // Platonic solids
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-tetrahedron",
    label: "Tetrahedron",
    generatePolygons: () => primitiveGeometry("tetrahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-cube",
    label: "Cube",
    generatePolygons: () => primitiveGeometry("cube"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-octahedron",
    label: "Octahedron",
    generatePolygons: () => primitiveGeometry("octahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-dodecahedron",
    label: "Dodecahedron",
    generatePolygons: () => primitiveGeometry("dodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-icosahedron",
    label: "Icosahedron",
    generatePolygons: () => primitiveGeometry("icosahedron"),
  },
  // Round / parametric
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-sphere",
    label: "Sphere",
    generatePolygons: () => primitiveGeometry("sphere"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-cylinder",
    label: "Cylinder",
    generatePolygons: () => uprightAlongZ(primitiveGeometry("cylinder")),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-cone",
    label: "Cone",
    generatePolygons: () => uprightAlongZ(primitiveGeometry("cone")),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-torus",
    label: "Torus",
    rotX: 75,
    generatePolygons: () => primitiveGeometry("torus"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-pyramid",
    label: "Pyramid",
    generatePolygons: () => uprightAlongZ(primitiveGeometry("pyramid")),
  },
  // Kepler-Poinsot star polyhedra
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-small-stellated-dodecahedron",
    label: "Small Stellated Dodecahedron",
    generatePolygons: () => primitiveGeometry("smallStellatedDodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-great-dodecahedron",
    label: "Great Dodecahedron",
    generatePolygons: () => primitiveGeometry("greatDodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-great-stellated-dodecahedron",
    label: "Great Stellated Dodecahedron",
    generatePolygons: () => primitiveGeometry("greatStellatedDodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-great-icosahedron",
    label: "Great Icosahedron",
    generatePolygons: () => primitiveGeometry("greatIcosahedron"),
  },
  // Archimedean solids
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-cuboctahedron",
    label: "Cuboctahedron",
    generatePolygons: () => primitiveGeometry("cuboctahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-icosidodecahedron",
    label: "Icosidodecahedron",
    generatePolygons: () => primitiveGeometry("icosidodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-truncated-tetrahedron",
    label: "Truncated Tetrahedron",
    generatePolygons: () => primitiveGeometry("truncatedTetrahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-truncated-cube",
    label: "Truncated Cube",
    generatePolygons: () => primitiveGeometry("truncatedCube"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-truncated-octahedron",
    label: "Truncated Octahedron",
    generatePolygons: () => primitiveGeometry("truncatedOctahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-truncated-dodecahedron",
    label: "Truncated Dodecahedron",
    generatePolygons: () => primitiveGeometry("truncatedDodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-truncated-icosahedron",
    label: "Truncated Icosahedron",
    generatePolygons: () => primitiveGeometry("truncatedIcosahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-truncated-cuboctahedron",
    label: "Truncated Cuboctahedron",
    generatePolygons: () => primitiveGeometry("truncatedCuboctahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-truncated-icosidodecahedron",
    label: "Truncated Icosidodecahedron",
    generatePolygons: () => primitiveGeometry("truncatedIcosidodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-rhombicuboctahedron",
    label: "Rhombicuboctahedron",
    generatePolygons: () => primitiveGeometry("rhombicuboctahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-rhombicosidodecahedron",
    label: "Rhombicosidodecahedron",
    generatePolygons: () => primitiveGeometry("rhombicosidodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-snub-cube",
    label: "Snub Cube",
    generatePolygons: () => primitiveGeometry("snubCube"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-snub-dodecahedron",
    label: "Snub Dodecahedron",
    generatePolygons: () => primitiveGeometry("snubDodecahedron"),
  },
  // Catalan solids
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-rhombic-dodecahedron",
    label: "Rhombic Dodecahedron",
    generatePolygons: () => primitiveGeometry("rhombicDodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-rhombic-triacontahedron",
    label: "Rhombic Triacontahedron",
    generatePolygons: () => primitiveGeometry("rhombicTriacontahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-triakis-tetrahedron",
    label: "Triakis Tetrahedron",
    generatePolygons: () => primitiveGeometry("triakisTetrahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-triakis-octahedron",
    label: "Triakis Octahedron",
    generatePolygons: () => primitiveGeometry("triakisOctahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-triakis-icosahedron",
    label: "Triakis Icosahedron",
    generatePolygons: () => primitiveGeometry("triakisIcosahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-tetrakis-hexahedron",
    label: "Tetrakis Hexahedron",
    generatePolygons: () => primitiveGeometry("tetrakisHexahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-pentakis-dodecahedron",
    label: "Pentakis Dodecahedron",
    generatePolygons: () => primitiveGeometry("pentakisDodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-disdyakis-dodecahedron",
    label: "Disdyakis Dodecahedron",
    generatePolygons: () => primitiveGeometry("disdyakisDodecahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-disdyakis-triacontahedron",
    label: "Disdyakis Triacontahedron",
    generatePolygons: () => primitiveGeometry("disdyakisTriacontahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-deltoidal-icositetrahedron",
    label: "Deltoidal Icositetrahedron",
    generatePolygons: () => primitiveGeometry("deltoidalIcositetrahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-deltoidal-hexecontahedron",
    label: "Deltoidal Hexecontahedron",
    generatePolygons: () => primitiveGeometry("deltoidalHexecontahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-pentagonal-icositetrahedron",
    label: "Pentagonal Icositetrahedron",
    generatePolygons: () => primitiveGeometry("pentagonalIcositetrahedron"),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-pentagonal-hexecontahedron",
    label: "Pentagonal Hexecontahedron",
    generatePolygons: () => primitiveGeometry("pentagonalHexecontahedron"),
  },
  // Parametric families
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-prism",
    label: "Prism (Hexagonal)",
    generatePolygons: () => uprightAlongZ(primitiveGeometry("prism")),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-antiprism",
    label: "Antiprism (Hexagonal)",
    generatePolygons: () => uprightAlongZ(primitiveGeometry("antiprism")),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-bipyramid",
    label: "Bipyramid (Hexagonal)",
    generatePolygons: () => uprightAlongZ(primitiveGeometry("bipyramid")),
  },
  {
    ...PRIMITIVE_DEFAULTS,
    id: "primitive-trapezohedron",
    label: "Trapezohedron (Pentagonal)",
    generatePolygons: () => uprightAlongZ(primitiveGeometry("trapezohedron")),
  },
];

export const PRESETS: PresetModel[] = [
  ...PRIMITIVE_PRESETS,
  {
    id: "chicken",
    label: "Chicken",
    category: "Characters",
    kind: "obj",
    url: "/gallery/obj/chicken.obj",
    mtlUrl: "/gallery/obj/chicken.mtl",
    options: { targetSize: 60, defaultColor: "#cccccc" },
    zoom: 0.15,
    rotX: 74.4,
    rotY: 301.6,
    attribution: GOOGLE_POLY_AMBER_ATTRIBUTION,
  },
  {
    id: "sting",
    label: "Sting Sword",
    category: "Weapons",
    kind: "obj",
    url: "/gallery/obj/sting.obj",
    options: {
      targetSize: 60,
      defaultColor: "#cccccc",
      materialTextures: { Sting: "/gallery/obj/sting-diffuse.png" },
    },
    galleryBucket: "Textured",
    zoom: 0.3,
    rotX: 65,
    rotY: 45,
    attribution: KANGAROOZ_STING_ATTRIBUTION,
  },
  {
    id: "cottage",
    label: "Cottage",
    category: "Architecture",
    kind: "obj",
    url: "/gallery/obj/cottage.obj",
    options: {
      targetSize: 60,
      defaultColor: "#a0a0a0",
      materialTextures: { cottage_texture: "/gallery/obj/cottage-diffuse.png" },
      includeObjects: ["Cube_Cube.002"],
    },
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: PROJECT_CHRONO_OFFROAD_ATTRIBUTION,
  },
  {
    id: "rock1",
    label: "Rock",
    category: "Environment",
    kind: "obj",
    url: "/gallery/obj/rock1.obj",
    mtlUrl: "/gallery/obj/rock1.mtl",
    options: { targetSize: 40, defaultColor: "#8b6f47", excludeObjects: ["Plane"] },
    galleryBucket: "Textured",
    zoom: 0.6,
    rotX: 65,
    rotY: 45,
    attribution: PROJECT_CHRONO_OFFROAD_ATTRIBUTION,
  },
  {
    id: "insurgent",
    label: "Ship - Insurgent",
    category: "Vehicles",
    kind: "gltf",
    url: "/gallery/glb/insurgent.gltf",
    options: { targetSize: 60 },
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: { ...QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION, tris: 3012 },
  },
  {
    id: "apoc-car",
    label: "Apocalypse Car",
    category: "Vehicles",
    kind: "glb",
    url: "/gallery/glb/apocalypse/car.glb",
    options: { targetSize: 60 },
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-barrel",
    label: "Apocalypse Barrel",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/barrel.glb",
    options: { targetSize: 50 },
    galleryBucket: "Textured",
    zoom: 0.5,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-tire",
    label: "Apocalypse Tire",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/tire.glb",
    options: { targetSize: 50 },
    galleryBucket: "Textured",
    zoom: 0.5,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-ground-planks",
    label: "Ground Planks",
    category: "Environment",
    kind: "glb",
    url: "/gallery/glb/apocalypse/ground_planks.glb",
    options: { targetSize: 60 },
    galleryBucket: "Textured",
    zoom: 0.55,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-jerry-can",
    label: "Jerry Can",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/jerry_can_with_nozzle.glb",
    options: { targetSize: 50 },
    galleryBucket: "Textured",
    zoom: 0.5,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-pallet-cluster",
    label: "Pallet Cluster",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/pallet_cluster_1.glb",
    options: { targetSize: 60 },
    galleryBucket: "Textured",
    zoom: 0.45,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-road-barrier",
    label: "Road Barrier",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/road_barrier.glb",
    options: { targetSize: 60 },
    galleryBucket: "Textured",
    zoom: 0.45,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-electric-pole",
    label: "Electric Pole",
    category: "Environment",
    kind: "glb",
    url: "/gallery/glb/apocalypse/electric_pole_1.glb",
    options: { targetSize: 70 },
    galleryBucket: "Textured",
    zoom: 0.35,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-wall-hole",
    label: "Wall with Hole",
    category: "Architecture",
    kind: "glb",
    url: "/gallery/glb/apocalypse/wall_1_hole.glb",
    options: { targetSize: 60 },
    galleryBucket: "Textured",
    zoom: 0.45,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-spike",
    label: "Spike Barricade",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/wooden_spike_barricade.glb",
    options: { targetSize: 60 },
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "tree",
    label: "Tree",
    category: "Environment",
    kind: "glb",
    url: "/gallery/glb/tree.glb",
    options: { targetSize: 60 },
    zoom: 0.3,
    rotX: 65,
    rotY: 45,
  },
  {
    id: "saucer",
    label: "Flying saucer",
    category: "Vehicles",
    kind: "glb",
    url: "/gallery/glb/poly-pizza/flying-saucer.glb",
    options: { targetSize: 60, defaultColor: "#94a3b8" },
    galleryBucket: "Textured",
    zoom: 0.2,
    rotX: 67,
    rotY: 42.3,
    attribution: GOOGLE_POLY_FLYING_SAUCER_ATTRIBUTION,
  },
  {
    id: "wheelbarrow",
    label: "Wheelbarrow",
    category: "Objects",
    kind: "obj",
    url: "/gallery/obj/wheelbarrow.obj",
    mtlUrl: "/gallery/obj/wheelbarrow.mtl",
    zoom: 0.8,
    rotX: 66.2,
    rotY: 36.1,
  },
  {
    id: "teapot",
    label: "Teapot",
    category: "Objects",
    kind: "obj",
    url: "/gallery/obj/teapot.obj",
    options: { targetSize: 60, defaultColor: "#a3a3a3" },
    zoom: 0.2,
    rotX: 65,
    rotY: 45,
    attribution: UTAH_TEAPOT_ATTRIBUTION,
  },
  {
    id: "castle",
    label: "Castle",
    category: "Architecture",
    kind: "obj",
    url: "/gallery/obj/castle.obj",
    options: { targetSize: 60 },
    zoom: 0.15,
    rotX: 66.9,
    rotY: 68.5,
    attribution: KENNEY_MINIGOLF_ATTRIBUTION,
  },
  {
    id: "coliseum",
    label: "Coliseum",
    category: "Architecture",
    kind: "obj",
    url: "/gallery/obj/coliseum.obj",
    options: { targetSize: 80, palette: ["#c9a876", "#a78760", "#8b6f47", "#6b5538"] },
    zoom: 0.15,
    rotX: 65,
    rotY: 45,
  },
  ...OBJ_PRESET_FILES.map(objPreset),
  ...STL_PRESET_FILES.map(stlPreset),
  ...GLB_PRESET_FILES.map(glbPreset),
  ...POLY_PIZZA_PRESET_FILES.map(glbPreset),
  ...VOX_PRESET_FILES.map(voxPreset),
];
