import type { GalleryPresetFile, ObjGalleryPresetFile, StlGalleryPresetFile } from "../types";
import {
  KHRONOS_FOX_ATTRIBUTION,
  KHRONOS_AVOCADO_ATTRIBUTION,
  GOOGLE_POLY_ASTRONAUT_ATTRIBUTION,
  MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION,
  MINI_MIKES_METRO_MINIS_ATTRIBUTION,
  MONOGON_DESERT_TOWN_ATTRIBUTION,
  MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION,
  MONOGON_COUNTRY_SIDE_ATTRIBUTION,
  MONOGON_CYBERPUNK_CITY_ATTRIBUTION,
  MONOGON_VOXEL_PLANE_ATTRIBUTION,
  MONOGON_VOXEL_MECHAS_ATTRIBUTION,
  MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION,
  SONA_SAR_VOXEL_ANIMALS_ITEMS_ATTRIBUTION,
  MAGICAVOXEL_TEST_MODELS_ATTRIBUTION,
  OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  OPENHV_VOXELS_ATTRIBUTION,
  FLOOOH_VOXEL_DATA_ATTRIBUTION,
  QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION,
  nasa3dAttribution,
  openGameArtAttribution,
  polyPizzaAttribution,
  quaterniusAttribution,
  smithsonianOpenAccessAttribution,
  thingiverseAttribution,
} from "./attributions";

const NASA_GLB_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "nasa/opportunity.glb",
    label: "Mars Rover Opportunity",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/mars-exploration-rover-opportunity-mer-b/",
      3754,
    ),
  },
  {
    file: "nasa/cubesat-1u.glb",
    label: "CubeSat 1U",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Christopher R. Meaney",
      "https://science.nasa.gov/3d-resources/cubesat-1-ru-generic/",
      6063,
    ),
  },
  {
    file: "nasa/tdrs-a.glb",
    label: "Tracking and Data Relay Satellite",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/tracking-and-data-relay-satellites-tdrs-a/",
      2936,
    ),
  },
  {
    file: "nasa/hubble-space-telescope.glb",
    label: "Hubble Space Telescope",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "DigitalSpace Corporation",
      "https://science.nasa.gov/3d-resources/hubble-space-telescope-a/",
      7670,
    ),
  },
  {
    file: "nasa/international-space-station.glb",
    label: "International Space Station",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/international-space-station-iss-a/",
      6628,
    ),
  },
  {
    file: "nasa/space-shuttle.glb",
    label: "Space Shuttle",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-b/",
      2473,
    ),
  },
  {
    file: "nasa/kepler.glb",
    label: "Kepler Space Telescope",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/kepler-b/",
      372,
    ),
  },
  {
    file: "nasa/grace.glb",
    label: "GRACE",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Brian E. Kumanchik; NASA/Christian A. Lopez",
      "https://science.nasa.gov/3d-resources/gravity-recovery-and-climate-experiment-grace-a/",
      3439,
    ),
  },
  {
    file: "nasa/icesat-a.glb",
    label: "ICESat",
    category: "Vehicles",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/ice-clouds-and-land-elevation-satellite-icesat-a/",
      976,
    ),
  },
  {
    file: "nasa/gamma-ray-observatory.glb",
    label: "Gamma Ray Observatory",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Christopher R. Meaney",
      "https://science.nasa.gov/3d-resources/gamma-ray-observatory/",
      4244,
    ),
  },
  {
    file: "nasa/wide-field-planetary-camera.glb",
    label: "Wide Field Planetary Camera",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "DigitalSpace Corporation",
      "https://science.nasa.gov/3d-resources/wide-field-planetary-camera/",
      224,
    ),
  },
  {
    file: "nasa/crew-lock-bag.glb",
    label: "Crew Lock Bag",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "DigitalSpace Corporation",
      "https://science.nasa.gov/3d-resources/crew-lock-bag/",
      506,
    ),
  },
  {
    file: "nasa/flight-system-support.glb",
    label: "Flight System Support",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "DigitalSpace Corporation",
      "https://science.nasa.gov/3d-resources/flight-system-support/",
      1292,
    ),
  },
  {
    file: "nasa/space-shuttle-eva-suit.glb",
    label: "EVA Suit",
    category: "Objects",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-parts/",
      6430,
    ),
  },
  {
    file: "nasa/orbiter-docking-system.glb",
    label: "Orbiter Docking System",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-parts/",
      5635,
    ),
  },
  {
    file: "nasa/space-shuttle-external-tank.glb",
    label: "Space Shuttle External Tank",
    category: "Vehicles",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-parts/",
      6326,
    ),
  },
  {
    file: "nasa/solid-rocket-booster.glb",
    label: "Solid Rocket Booster",
    category: "Vehicles",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-parts/",
      4136,
    ),
  },
];

const SMITHSONIAN_GLB_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "smithsonian/morse-telegraph-key.glb",
    label: "Morse-Vail Telegraph Key",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: smithsonianOpenAccessAttribution(
      "https://www.si.edu/object/morse-vail-telegraph-key%3Anmah_1096762",
      3600,
    ),
  },
];

export const GLB_PRESET_FILES: GalleryPresetFile[] = [
  { file: "FishAnimated.glb", label: "Animated Fish", category: "Animated" },
  { file: "ClownfishAnimated.glb", label: "Animated Clownfish", category: "Animated" },
  { file: "AnimatedWizard.glb", label: "Animated Wizard", category: "Animated" },
  {
    file: "khronos/animated-fox.glb",
    label: "Animated Fox",
    category: "Animated",
    attribution: KHRONOS_FOX_ATTRIBUTION,
  },
  {
    file: "opengameart/animated-pliers.glb",
    label: "Animated Pliers",
    category: "Animated",
    attribution: openGameArtAttribution("LonesomeDucky", "tool-pack-2", 1452),
  },
  {
    file: "opengameart/animated-utility-knife.glb",
    label: "Animated Utility Knife",
    category: "Animated",
    attribution: openGameArtAttribution("LonesomeDucky", "tool-pack-2", 576),
  },
  { file: "AnimatedMushnub.glb", label: "Animated Mushnub", category: "Animated" },
  { file: "AnimatedSnake.glb", label: "Animated Snake", category: "Animated" },
  { file: "Bat.glb", category: "Animals" },
  { file: "Bear.glb", category: "Animals" },
  { file: "Cat.glb", category: "Animals" },
  { file: "Cheetah.glb", category: "Animals" },
  { file: "Deer.glb", category: "Animals" },
  { file: "Dinosaur.glb", category: "Animals" },
  { file: "Dog.glb", category: "Animals" },
  { file: "Dolphin.glb", category: "Animals" },
  { file: "Dragon.glb", category: "Animals" },
  { file: "Duck.glb", category: "Animals" },
  { file: "Elephant.glb", category: "Animals" },
  { file: "Fly.glb", category: "Animals" },
  { file: "Frog.glb", category: "Animals" },
  { file: "Gorilla.glb", category: "Animals" },
  { file: "Hippo.glb", category: "Animals" },
  { file: "Horse.glb", category: "Animals" },
  { file: "Koala.glb", category: "Animals" },
  { file: "Lobster.glb", category: "Animals" },
  { file: "Octopus.glb", category: "Animals" },
  { file: "Owl.glb", category: "Animals" },
  { file: "Pig.glb", category: "Animals" },
  { file: "Poodle.glb", category: "Animals" },
  { file: "Rat.glb", category: "Animals" },
  { file: "Robin.glb", category: "Animals" },
  { file: "Scorpion.glb", category: "Animals" },
  { file: "Shark.glb", category: "Animals" },
  { file: "Snail.glb", category: "Animals" },
  { file: "Wolf.glb", category: "Animals" },
  { file: "Zebra.glb", category: "Animals" },
  { file: "Bicycle.glb", category: "Vehicles" },
  { file: "Dump truck.glb", label: "Dump Truck", category: "Vehicles" },
  { file: "Policecar.glb", label: "Police Car", category: "Vehicles" },
  { file: "Taxi.glb", category: "Vehicles" },
  { file: "Truck.glb", category: "Vehicles" },
  ...NASA_GLB_PRESET_FILES,
  {
    file: "model-viewer/astronaut.glb",
    label: "Astronaut",
    category: "Characters",
    galleryBucket: "Textured",
    attribution: GOOGLE_POLY_ASTRONAUT_ATTRIBUTION,
  },
  { file: "Acousticguitar.glb", label: "Guitar (Acoustic)", category: "Instruments" },
  { file: "Electricguitar.glb", label: "Guitar (Electric)", category: "Instruments" },
  { file: "Saxophone.glb", category: "Instruments" },
  { file: "Trumpet.glb", category: "Instruments" },
  { file: "Violin.glb", category: "Instruments" },
  ...SMITHSONIAN_GLB_PRESET_FILES,
  { file: "apple.glb", label: "Apple", category: "Food & Drink" },
  {
    file: "khronos/avocado.glb",
    label: "Avocado",
    category: "Food & Drink",
    galleryBucket: "Textured",
    attribution: KHRONOS_AVOCADO_ATTRIBUTION,
  },
  { file: "BottleChampagne.glb", label: "Champagne Bottle", category: "Food & Drink" },
  { file: "Eggplant.glb", category: "Food & Drink" },
  { file: "Grapes.glb", category: "Food & Drink" },
  { file: "Hot dog.glb", label: "Hot Dog", category: "Food & Drink" },
  { file: "Watermelon.glb", category: "Food & Drink" },
  { file: "Cactus.glb", category: "Environment" },
  { file: "Campfire.glb", category: "Environment" },
  { file: "Drill.glb", category: "Objects" },
  { file: "Globe.glb", category: "Objects" },

  // Medieval Village Pack — compact standalone set.
  { file: "medieval/Bags.glb", category: "Medieval Village" },
  { file: "medieval/Barrel.glb", category: "Medieval Village" },
  { file: "medieval/Bell.glb", category: "Medieval Village" },
  { file: "medieval/Bonfire.glb", category: "Medieval Village" },
  { file: "medieval/Cart.glb", category: "Medieval Village" },
  { file: "medieval/Cauldron.glb", category: "Medieval Village" },
  { file: "medieval/Crate.glb", label: "Medieval Crate", category: "Medieval Village" },
  { file: "medieval/Package.glb", category: "Medieval Village" },
  { file: "medieval/Package-kYvD6QCQRd.glb", label: "Package (Small)", category: "Medieval Village" },
  { file: "medieval/Path Straight.glb", label: "Path Straight", category: "Medieval Village" },
  { file: "medieval/Rocks.glb", category: "Medieval Village" },
  { file: "medieval/Sawmill Saw.glb", label: "Sawmill Saw", category: "Medieval Village" },
  { file: "medieval/Smoke.glb", category: "Medieval Village" },
  { file: "medieval/Well.glb", category: "Medieval Village" },
  { file: "medieval/Window.glb", category: "Medieval Village" },
  { file: "medieval/Window-EY1zrFcme9.glb", label: "Window (Tall)", category: "Medieval Village" },

  // City Kit — compact Solid building set.
  { file: "city/Skyscraper.glb", category: "City Kit" },
  { file: "city/Large Building.glb", label: "Large Building", category: "City Kit" },
  { file: "city/Small Building.glb", label: "Small Building", category: "City Kit" },

  // Urban Pack — cars + street furniture + a few characters.
  { file: "urban/Road Bits.glb", label: "Road", category: "Urban Pack" },
  { file: "urban/Manhole Cover.glb", label: "Manhole Cover", category: "Urban Pack" },
  { file: "urban/Car.glb", category: "Urban Pack" },
  { file: "urban/SUV.glb", category: "Urban Pack" },
  { file: "urban/Van.glb", category: "Urban Pack" },
  { file: "urban/Pickup Truck.glb", label: "Pickup Truck", category: "Urban Pack" },
  { file: "urban/Bus.glb", label: "City Bus", category: "Urban Pack" },
  { file: "urban/Sports Car.glb", label: "Sports Car", category: "Urban Pack" },
  { file: "urban/Police Car.glb", label: "Police Cruiser", category: "Urban Pack" },
  { file: "urban/Motorcycle.glb", category: "Urban Pack" },
  { file: "urban/Stop sign.glb", label: "Stop Sign", category: "Urban Pack" },
  { file: "urban/Billboard.glb", category: "Urban Pack", galleryBucket: "Textured" },
  { file: "urban/Dumpster.glb", category: "Urban Pack" },
  { file: "urban/Mailbox.glb", category: "Urban Pack" },
  { file: "urban/Fire hydrant.glb", label: "Fire Hydrant", category: "Urban Pack" },
  { file: "urban/Cone.glb", label: "Traffic Cone", category: "Urban Pack" },
  { file: "urban/Box.glb", label: "Urban Box", category: "Urban Pack" },
  { file: "urban/Power Box.glb", label: "Power Box", category: "Urban Pack" },
  { file: "urban/Air conditioner.glb", label: "Air Conditioner", category: "Urban Pack" },
  { file: "urban/ATM.glb", category: "Urban Pack" },
  { file: "urban/Planter & Bushes.glb", label: "Planter & Bushes", category: "Urban Pack" },
  { file: "urban/Man.glb", label: "Urban Man", category: "Urban Pack" },
  { file: "urban/Animated Woman.glb", label: "Woman", category: "Urban Pack" },
];

const CURATED_STL_PRESET_FILES: StlGalleryPresetFile[] = [
  {
    file: "castle-68679.stl",
    label: "Castle",
    category: "CAD",
    attribution: thingiverseAttribution("mazels", 22323, 2064),
  },
  {
    file: "chichen-itza-47076.stl",
    label: "Chichen Itza",
    category: "CAD",
    attribution: thingiverseAttribution("ramenspork", 14328, 1532, "Creative Commons - Attribution - Share Alike"),
  },
  {
    file: "low-poly-vase-100423.stl",
    label: "Low Poly Vase",
    category: "CAD",
    attribution: thingiverseAttribution("kikko_fr", 34999, 276, "Creative Commons - Attribution - Share Alike"),
  },
  {
    file: "low-poly-bunny-293137.stl",
    label: "Low Poly Bunny",
    category: "CAD",
    attribution: thingiverseAttribution("johnny6", 151081, 292, "Creative Commons - Attribution - Share Alike"),
  },
  {
    file: "heart-gear-39461.stl",
    label: "Heart Gear",
    category: "CAD",
    attribution: thingiverseAttribution("emmett", 12208, 1934, "Creative Commons - Attribution - Share Alike"),
  },
  {
    file: "gyroscopic-snowflake-105230.stl",
    label: "Gyroscopic Snowflake",
    category: "CAD",
    attribution: thingiverseAttribution("roman_hegglin", 36922, 1036),
  },
  {
    file: "skeletal-cubes-73453.stl",
    label: "Skeletal Cubes",
    category: "CAD",
    attribution: thingiverseAttribution("AuntDaisy", 24274, 1550, "Creative Commons - Attribution - Share Alike"),
  },
  {
    file: "hilbert-cube-53749.stl",
    label: "Hilbert Cube",
    category: "CAD",
    attribution: thingiverseAttribution("tbuser", 16343, 492, "Creative Commons - Attribution - Share Alike"),
  },
  {
    file: "cubist-torus-107100.stl",
    label: "Cubist Torus",
    category: "CAD",
    attribution: thingiverseAttribution("hudson", 37634, 4560),
  },
  {
    file: "six-cubes-compound-91658.stl",
    label: "Six Cubes Compound",
    category: "CAD",
    attribution: thingiverseAttribution("pmoews", 31520, 504),
  },
  {
    file: "johnson-ornament-j68-103287.stl",
    label: "Johnson Ornament J68",
    category: "CAD",
    attribution: thingiverseAttribution("pmoews", 36119, 690),
  },
  {
    file: "rhombic-chain-90794.stl",
    label: "Rhombic Chain",
    category: "CAD",
    attribution: thingiverseAttribution("emmett", 31151, 1224, "Creative Commons - Attribution - Share Alike"),
  },
  {
    file: "cube-in-sphere-49333.stl",
    label: "Cube In Sphere",
    category: "CAD",
    attribution: thingiverseAttribution("clintkc", 14878, 2464, "Public Domain"),
  },
  {
    file: "rocket-nose-cone-51316.stl",
    label: "Rocket Nose Cone",
    category: "CAD",
    attribution: thingiverseAttribution("MakerBotWorkshop", 15582, 1860, "Creative Commons - Attribution - Share Alike"),
  },
  {
    file: "venus-bust-73464.stl",
    label: "Venus Bust",
    category: "CAD",
    attribution: thingiverseAttribution("richgain", 24188, 1000),
  },
];

export const STL_PRESET_FILES: StlGalleryPresetFile[] = CURATED_STL_PRESET_FILES;

export const POLY_PIZZA_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "poly-pizza/fruit-crate.glb",
    label: "Fruit Crate",
    category: "Food & Drink",
    attribution: {
      creator: "BlenderVoyage",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/aXulVWHOeV",
      tris: 196,
    },
  },
  {
    file: "poly-pizza/pizza-slice.glb",
    label: "Pizza Slice",
    category: "Food & Drink",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/CA4HtaaMJn",
      tris: 392,
    },
  },
  {
    file: "poly-pizza/sheep.glb",
    label: "Sheep",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/C39AUXUUes",
      tris: 610,
    },
  },
  {
    file: "poly-pizza/large-building.glb",
    label: "Large Building",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/yKo7F36Qk2",
      tris: 950,
    },
  },
  {
    file: "poly-pizza/animated-robot.glb",
    label: "Animated Robot",
    category: "Animated",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/QCm7qe9uNJ",
      tris: 1425,
    },
  },
  {
    file: "poly-pizza/bird.glb",
    label: "Bird",
    category: "Animals",
    galleryBucket: "Textured",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/gYYC0gYMnw",
      tris: 1204,
    },
  },
  {
    file: "poly-pizza/cow.glb",
    label: "Cow",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/5XSc2Fka3F",
      tris: 796,
    },
  },
  {
    file: "poly-pizza/ducky.glb",
    label: "Ducky",
    category: "Animals",
    galleryBucket: "Textured",
    attribution: {
      creator: "Isa Lousberg",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/gt2eYOyOvU",
      tris: 604,
    },
  },
  {
    file: "poly-pizza/fish.glb",
    label: "Fish",
    category: "Animals",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/HkUAXudvBt",
      tris: 233,
    },
  },
  {
    file: "poly-pizza/llama.glb",
    label: "Llama",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/JxVJ9rfWGy",
      tris: 661,
    },
  },
  {
    file: "poly-pizza/pug.glb",
    label: "Pug",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/1gXKv15ik8",
      tris: 644,
    },
  },
  {
    file: "poly-pizza/guard-tower.glb",
    label: "Guard Tower",
    category: "Architecture",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/sbaM8I229r",
      tris: 344,
    },
  },
  {
    file: "poly-pizza/house.glb",
    label: "House",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/7VSVwAg2T3",
      tris: 381,
    },
  },
  {
    file: "poly-pizza/skyscraper.glb",
    label: "Skyscraper",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/XST1j6kYsL",
      tris: 456,
    },
  },
  {
    file: "poly-pizza/tower.glb",
    label: "Tower",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/5lvG0WtuTU",
      tris: 683,
    },
  },
  {
    file: "poly-pizza/two-story-house.glb",
    label: "Two story house",
    category: "Architecture",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/sGgL4Nt7I7",
      tris: 630,
    },
  },
  {
    file: "poly-pizza/watch-tower.glb",
    label: "Watch Tower",
    category: "Architecture",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/f2J0aSLVi4",
      tris: 656,
    },
  },
  {
    file: "poly-pizza/bucket.glb",
    label: "Bucket",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/tKTttwROq7",
      tris: 532,
    },
  },
  {
    file: "poly-pizza/can.glb",
    label: "Can",
    category: "Objects",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/YnowJvWqxE",
      tris: 428,
    },
  },
  {
    file: "poly-pizza/bread.glb",
    label: "Bread",
    category: "Food & Drink",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/luo9BHRaax",
      tris: 116,
    },
  },
  {
    file: "poly-pizza/cup-tea.glb",
    label: "Cup Tea",
    category: "Food & Drink",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/FUSyrlibw0",
      tris: 108,
    },
  },
  {
    file: "poly-pizza/egg-fried.glb",
    label: "Egg Fried",
    category: "Food & Drink",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/NVrB2yd66v",
      tris: 101,
    },
  },
  {
    file: "poly-pizza/rock.glb",
    label: "Rock",
    category: "Environment",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/cBqdRdLDDL",
      tris: 120,
    },
  },
  {
    file: "poly-pizza/rock-medium.glb",
    label: "Rock Medium",
    category: "Environment",
    galleryBucket: "Textured",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/s1OJ3bBzqc",
      tris: 342,
    },
  },
  {
    file: "poly-pizza/box.glb",
    label: "Box",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: {
      creator: "Kay Lousberg",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/ykZ23x9d6p",
      tris: 32,
    },
  },
  {
    file: "poly-pizza/empty-box.glb",
    label: "Empty Box",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: {
      creator: "CreativeTrio",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/pZBpmjtvw8",
      tris: 76,
    },
  },
  {
    file: "poly-pizza/animated-human.glb",
    label: "Animated Human",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/c3Ibh9I3udk",
      tris: 1578,
    },
  },
  {
    file: "poly-pizza/character-animated.glb",
    label: "Character Animated",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/DgOCW9ZCRJ",
      tris: 1246,
    },
  },
  {
    file: "poly-pizza/human-dude-guy.glb",
    label: "Human Dude Guy",
    category: "Characters",
    attribution: {
      creator: "hat_my_guy",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/83DpVkzvWk",
      tris: 1151,
    },
  },
  {
    file: "poly-pizza/man.glb",
    label: "Man",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/HMnuH5geEG",
      tris: 1216,
    },
  },
  {
    file: "poly-pizza/rabbit-blond.glb",
    label: "Rabbit Blond",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/cMsI6FDhNx",
      tris: 1570,
    },
  },
  {
    file: "poly-pizza/arrow.glb",
    label: "Arrow",
    category: "Weapons",
    galleryBucket: "Textured",
    attribution: {
      creator: "CreativeTrio",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/dZVjrxZdaB",
      tris: 119,
    },
  },
  {
    file: "poly-pizza/sword.glb",
    label: "Sword",
    category: "Weapons",
    attribution: {
      creator: "hat_my_guy",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/FvUHJZzy1M",
      tris: 141,
    },
  },
  {
    file: "poly-pizza/broccoli.glb",
    label: "Broccoli",
    category: "Food & Drink",
    attribution: polyPizzaAttribution("jeremy", "e2Z3XDxtT41", "CC-BY 3.0", 900),
  },
  {
    file: "poly-pizza/peanut.glb",
    label: "Peanut",
    category: "Food & Drink",
    attribution: polyPizzaAttribution("jeremy", "f57FFcX01Tr", "CC-BY 3.0", 1820),
  },
  {
    file: "poly-pizza/tomato.glb",
    label: "Tomato",
    category: "Food & Drink",
    attribution: polyPizzaAttribution("jeremy", "dcvfRb1X5JE", "CC-BY 3.0", 144),
  },
  {
    file: "poly-pizza/pear.glb",
    label: "Pear",
    category: "Food & Drink",
    attribution: polyPizzaAttribution("jeremy", "3Mp-3PRh7Tb", "CC-BY 3.0", 152),
  },
  {
    file: "poly-pizza/ice-cream.glb",
    label: "Ice Cream",
    category: "Food & Drink",
    attribution: polyPizzaAttribution("jeremy", "27NZ4ejbkZl", "CC-BY 3.0", 408),
  },
  {
    file: "poly-pizza/apple-tree.glb",
    label: "Apple Tree",
    category: "Environment",
    attribution: polyPizzaAttribution("jeremy", "2BUc5iO4nUo", "CC-BY 3.0", 644),
  },
  {
    file: "poly-pizza/triceratops.glb",
    label: "Triceratops",
    category: "Animals",
    attribution: polyPizzaAttribution("jeremy", "7GKj5zdc1RZ", "CC-BY 3.0", 892),
  },
  {
    file: "poly-pizza/tiger.glb",
    label: "Tiger",
    category: "Animals",
    attribution: polyPizzaAttribution("jeremy", "54KLm0HdFWy", "CC-BY 3.0", 892),
  },
  {
    file: "poly-pizza/monkey.glb",
    label: "Monkey",
    category: "Animals",
    attribution: polyPizzaAttribution("jeremy", "2mYaCEbogPq", "CC-BY 3.0", 680),
  },
  {
    file: "poly-pizza/crab.glb",
    label: "Crab",
    category: "Animals",
    attribution: polyPizzaAttribution("jeremy", "bmZ6-LnPmp0", "CC-BY 3.0", 768),
  },
  {
    file: "poly-pizza/turkey.glb",
    label: "Turkey",
    category: "Animals",
    attribution: polyPizzaAttribution("jeremy", "b3E2cqagRPn", "CC-BY 3.0", 336),
  },
  {
    file: "poly-pizza/mr-brush.glb",
    label: "Mr. Brush",
    category: "Objects",
    attribution: polyPizzaAttribution("jeremy", "0jKuzkEIurU", "CC-BY 3.0", 4644),
  },
  {
    file: "poly-pizza/animated-fox-quaternius.glb",
    label: "Animated Fox",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/Bc97C66HKi", 1848),
  },
  {
    file: "poly-pizza/animated-husky.glb",
    label: "Animated Husky",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/wcWiuEqwzq", 1920),
  },
  {
    file: "poly-pizza/animated-shiba-inu.glb",
    label: "Animated Shiba Inu",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/y4wdQpg767", 1950),
  },
  {
    file: "poly-pizza/animated-whale.glb",
    label: "Animated Whale",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/JGFwp6xWgk", 444),
  },
  {
    file: "poly-pizza/animated-shark.glb",
    label: "Animated Shark",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/sZR8AMLMz5", 1310),
  },
  {
    file: "poly-pizza/animated-enemy-small.glb",
    label: "Animated Enemy Small",
    category: "Characters",
    galleryBucket: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/4LjT020LQh", 1572),
  },
  {
    file: "poly-pizza/animated-slime-enemy.glb",
    label: "Animated Slime Enemy",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/eSLKTsbl7F", 1968),
  },
];

function voxFiles(
  files: string[],
  attribution: GalleryPresetFile["attribution"],
): GalleryPresetFile[] {
  return files.map((file) => ({ file, category: "VOX", attribution }));
}

const MINI_MIKES_METRO_MINIS_VOX_FILES: string[] = [
  "alien_bot1.vox",
  "alien_engi1a.vox",
  "alien_eye1a.vox",
  "chr_chef.vox",
  "chr_cop1.vox",
  "chr_hazmat1.vox",
  "chr_janitor.vox",
  "chr_paramedic2.vox",
  "chr_punk.vox",
  "chr_riotcop.vox",
  "chr_scientist.vox",
  "chr_super1.vox",
  "chr_thief.vox",
  "chr_zombie4.vox",
  "mob_cat1.vox",
  "mob_penguin.vox",
  "obj_arcade1.vox",
  "obj_boxingring.vox",
  "obj_busstop.vox",
  "obj_candle.vox",
  "obj_cart1a.vox",
  "obj_container4.vox",
  "obj_pumpkin.vox",
  "piano.vox",
  "scene_checkpoint.vox",
  "scene_coffee.vox",
  "scene_hazmat.vox",
  "scene_protest.vox",
  "scene_zombies.vox",
  "veh_ambulance.vox",
  "veh_cab1.vox",
  "veh_car1.vox",
  "veh_fire.vox",
  "veh_lunch1.vox",
  "veh_mini1.vox",
  "veh_police1.vox",
  "veh_suv1.vox",
  "veh_train.vox",
  "veh_truck1.vox",
];

const MAGICAVOXEL_TEST_MODEL_FILES: string[] = [
  "chr_knight.vox",
];

const OPENGAMEART_BUILDING_VOX_FILES: GalleryPresetFile[] = [
  {
    file: "opengameart-buildings/building-01.vox",
    label: "Building 01",
    category: "VOX",
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
  {
    file: "opengameart-buildings/building-02.vox",
    label: "Building 02",
    category: "VOX",
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
  {
    file: "opengameart-buildings/tower-01.vox",
    label: "Tower",
    category: "VOX",
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
  {
    file: "opengameart-buildings/mini-building-01.vox",
    label: "Small Building 01",
    category: "VOX",
    targetSize: 45,
    zoom: 0.55,
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
  {
    file: "opengameart-buildings/mini-building-02.vox",
    label: "Small Building 02",
    category: "VOX",
    targetSize: 45,
    zoom: 0.55,
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
];

const OPENHV_VOX_FILES: GalleryPresetFile[] = [
  { file: "openhv/battleship.vox", label: "Battleship", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
  { file: "openhv/dropship.vox", label: "Dropship", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
  { file: "openhv/firetruck.vox", label: "Fire Truck", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
  { file: "openhv/saucer.vox", label: "Saucer", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
  { file: "openhv/turtle.vox", label: "Turtle", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
];

const FLOOOH_VOX_FILES: GalleryPresetFile[] = [
  { file: "floooh/cassette.vox", label: "Cassette", category: "VOX", targetSize: 35, zoom: 0.7, attribution: FLOOOH_VOXEL_DATA_ATTRIBUTION },
  { file: "floooh/kc85-computer.vox", label: "KC85 Computer", category: "VOX", attribution: FLOOOH_VOXEL_DATA_ATTRIBUTION },
  { file: "floooh/kc85-keyboard.vox", label: "KC85 Keyboard", category: "VOX", targetSize: 35, zoom: 0.6, attribution: FLOOOH_VOXEL_DATA_ATTRIBUTION },
  { file: "floooh/lcr-c.vox", label: "LCR-C", category: "VOX", targetSize: 45, zoom: 0.5, attribution: FLOOOH_VOXEL_DATA_ATTRIBUTION },
];

export const VOX_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "AncientCrashSite.vox",
    label: "Ancient Crash Site",
    category: "VOX",
    targetSize: 70,
    zoom: 0.35,
    attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION,
  },
  { file: "army.vox", label: "Army", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "desert.vox", label: "Desert", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "desert2.vox", label: "Desert 2", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "Garden.vox", category: "VOX", attribution: MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION },
  { file: "Building03.vox", label: "Building 03", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "HUT.vox", label: "Hut", category: "VOX", attribution: MONOGON_COUNTRY_SIDE_ATTRIBUTION },
  { file: "house.vox", label: "House", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "pyramid.vox", label: "Pyramid", category: "VOX", attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION },
  { file: "skyscraper.vox", label: "Skyscraper", category: "VOX", attribution: MONOGON_CYBERPUNK_CITY_ATTRIBUTION },
  { file: "stairs.vox", label: "Stairs", category: "VOX", attribution: MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION },
  { file: "Plane_03.vox", label: "Plane 03", category: "VOX", attribution: MONOGON_VOXEL_PLANE_ATTRIBUTION },
  { file: "bus.vox", label: "Bus", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "tank.vox", label: "Tank", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "arachnoid.vox", label: "Arachnoid", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "MechaGolem.vox", label: "Mecha Golem", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "mecha.vox", label: "Mecha", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "StarMarineTrooper.vox", label: "Star Marine Trooper", category: "VOX", attribution: MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION },
  { file: "apple.vox", label: "Apple", category: "VOX", attribution: SONA_SAR_VOXEL_ANIMALS_ITEMS_ATTRIBUTION },
  { file: "dual.vox", label: "Dual", category: "VOX", attribution: MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION },
  { file: "Treasure.vox", category: "VOX", attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION },
  { file: "tree.vox", label: "Tree", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  ...OPENGAMEART_BUILDING_VOX_FILES,
  ...OPENHV_VOX_FILES,
  ...FLOOOH_VOX_FILES,
  { file: "chr_robot.vox", label: "Voxel Robot", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "horse.vox", label: "Voxel Horse", category: "VOX", attribution: MAGICAVOXEL_TEST_MODELS_ATTRIBUTION },
  { file: "mob_bear.vox", label: "Voxel Bear", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "obj_campfire.vox", label: "Voxel Campfire", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "scene_train.vox", label: "Train Scene", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  ...voxFiles(MINI_MIKES_METRO_MINIS_VOX_FILES, MINI_MIKES_METRO_MINIS_ATTRIBUTION),
  ...voxFiles(MAGICAVOXEL_TEST_MODEL_FILES, MAGICAVOXEL_TEST_MODELS_ATTRIBUTION),
];

const ULTIMATE_SPACESHIPS_ROOT = "quaternius/ultimate-spaceships";

export function ultimateSpaceshipPreset(
  slug: string,
  name: string,
  textureFile: string,
  tris: number,
): ObjGalleryPresetFile {
  return {
    file: `${ULTIMATE_SPACESHIPS_ROOT}/${slug}/${name}.obj`,
    label: `Ship - ${name}`,
    category: "Vehicles",
    galleryBucket: "Textured",
    options: {
      materialTextures: {
        Texture: `/gallery/obj/${ULTIMATE_SPACESHIPS_ROOT}/${slug}/${textureFile}`,
      },
    },
    zoom: 0.24,
    attribution: { ...QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION, tris },
  };
}

export const OBJ_PRESET_FILES: ObjGalleryPresetFile[] = [
  {
    file: "opengameart/crate/Box.obj",
    label: "Crate",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("Kutejnikov", "crate-5", 12),
  },
  {
    file: "opengameart/hay-bale/hay_bale.obj",
    label: "Hay Bale",
    category: "Environment",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("Mish7913", "hay-bale-0", 108),
  },
  {
    file: "opengameart/low-poly-car/car.obj",
    label: "Low Poly Car",
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.3,
    attribution: openGameArtAttribution("drummyfish", "low-poly-car-3", 228),
  },
  {
    file: "opengameart/wood-crate/woodcrate.obj",
    label: "Wood Crate",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("GGBotNet", "wood-crate-3d", 284),
  },
  {
    file: "opengameart/broken-stone-slab/stone.obj",
    label: "Broken Stone Slab",
    category: "Environment",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("Kutejnikov", "broken-stone-slab", 186),
  },
  {
    file: "opengameart/frog-guy/frog.obj",
    label: "Frog Guy",
    category: "Characters",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("drummyfish", "frog-guy", 356),
  },
  {
    file: "opengameart/game-cartridge/cartridge.obj",
    label: "Game Cartridge",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("Kutejnikov", "game-cartridge", 432, "CC-BY 4.0"),
  },
  {
    file: "opengameart/fire-extinguisher/extinguisher.obj",
    label: "Fire Extinguisher",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("cron", "fire-extinguisher-2", 818, "CC-BY-SA 4.0"),
  },
  {
    file: "opengameart/keycard/keycard.obj",
    label: "Keycard",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("codeinfernogames", "3d-keycard", 20),
  },
  {
    file: "opengameart/pirate-coin/pirate-coin.obj",
    label: "Pirate Coin",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("acasas", "3d-pirate-coin", 624, "CC-BY 3.0"),
  },
  {
    file: "opengameart/perfume-bottle/perfume.obj",
    label: "Perfume Bottle",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("PantherOne", "perfume-bottle-persian", 196, "CC-BY 3.0"),
  },
  {
    file: "opengameart/grandfather-clock/grandfather-clock.obj",
    label: "Grandfather Clock",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("GGBotNet", "grandfather-clock-3d", 106, "CC-BY 4.0"),
  },
  {
    file: "opengameart/old-book/old-book.obj",
    label: "Old Book",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("GGBotNet", "old-bible-3d", 60, "CC-BY 4.0"),
  },
  {
    file: "opengameart/haunted-house/hauntedhouse.obj",
    label: "Haunted House",
    category: "Buildings",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("naovia", "haunted-house", 377),
  },
  {
    file: "opengameart/biplane/biplane.obj",
    label: "Low Poly Biplane",
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.25,
    attribution: openGameArtAttribution("mfep", "low-poly-biplane", 668),
  },
  ultimateSpaceshipPreset("challenger", "Challenger", "Challenger_Green.png", 1748),
  ultimateSpaceshipPreset("executioner", "Executioner", "Executioner_Blue.png", 3388),
  ultimateSpaceshipPreset("omen", "Omen", "Omen_Orange.png", 1426),
  ultimateSpaceshipPreset("pancake", "Pancake", "Pancake_Orange.png", 2688),
  ultimateSpaceshipPreset("spitfire", "Spitfire", "Spitfire_Red.png", 3512),
  ultimateSpaceshipPreset("zenith", "Zenith", "Zenith_Red.png", 2152),
  {
    file: "quaternius/nature/Lilypad.obj",
    label: "Lilypad",
    category: "Environment",
    zoom: 0.45,
    attribution: quaterniusAttribution("https://quaternius.com/packs/ultimatenature.html", 372),
  },
  {
    file: "quaternius/dungeon/Chest_gold.obj",
    label: "Treasure Chest",
    category: "Objects",
    zoom: 0.4,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 436),
  },
  {
    file: "quaternius/dungeon/Torch.obj",
    label: "Torch",
    category: "Objects",
    zoom: 0.35,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 518),
  },
  {
    file: "quaternius/dungeon/Candelabrum.obj",
    label: "Candelabrum",
    category: "Objects",
    zoom: 0.35,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 636),
  },
];
