import type { PresetModel } from "../types";
import {
  GOOGLE_POLY_AMBER_ATTRIBUTION,
  KANGAROOZ_STING_ATTRIBUTION,
  PROJECT_CHRONO_OFFROAD_ATTRIBUTION,
  QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION,
  ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  GOOGLE_POLY_FLYING_SAUCER_ATTRIBUTION,
  UTAH_TEAPOT_ATTRIBUTION,
  KENNEY_MINIGOLF_ATTRIBUTION,
} from "./attributions";
import { GLB_PRESET_FILES, POLY_PIZZA_PRESET_FILES, VOX_PRESET_FILES, OBJ_PRESET_FILES } from "./presetFiles";
import { glbPreset, objPreset, voxPreset } from "./presetBuilders";

export const PRESETS: PresetModel[] = [
  {
    id: "chicken",
    label: "Chicken",
    category: "Characters",
    kind: "obj",
    url: "/gallery/obj/chicken.obj",
    mtlUrl: "/gallery/obj/chicken.mtl",
    zoom: 0.15,
    rotX: 74.4,
    rotY: 301.6,
    attribution: GOOGLE_POLY_AMBER_ATTRIBUTION,
  },
  {
    id: "sting",
    label: "Sting Sword",
    category: "Weapons",
    kind: "obj",
    url: "/gallery/obj/sting.obj",
    galleryBucket: "Textured",
    zoom: 0.3,
    rotX: 65,
    rotY: 45,
    attribution: KANGAROOZ_STING_ATTRIBUTION,
  },
  {
    id: "cottage",
    label: "Cottage",
    category: "Architecture",
    kind: "obj",
    url: "/gallery/obj/cottage.obj",
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: PROJECT_CHRONO_OFFROAD_ATTRIBUTION,
  },
  {
    id: "rock1",
    label: "Rock",
    category: "Environment",
    kind: "obj",
    url: "/gallery/obj/rock1.obj",
    mtlUrl: "/gallery/obj/rock1.mtl",
    galleryBucket: "Textured",
    zoom: 0.6,
    rotX: 65,
    rotY: 45,
    attribution: PROJECT_CHRONO_OFFROAD_ATTRIBUTION,
  },
  {
    id: "insurgent",
    label: "Ship - Insurgent",
    category: "Vehicles",
    kind: "gltf",
    url: "/gallery/glb/insurgent.gltf",
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: { ...QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION, tris: 3012 },
  },
  {
    id: "apoc-car",
    label: "Apocalypse Car",
    category: "Vehicles",
    kind: "glb",
    url: "/gallery/glb/apocalypse/car.glb",
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-barrel",
    label: "Apocalypse Barrel",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/barrel.glb",
    galleryBucket: "Textured",
    zoom: 0.5,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-spike",
    label: "Spike Barricade",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/wooden_spike_barricade.glb",
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "tree",
    label: "Tree",
    category: "Environment",
    kind: "glb",
    url: "/gallery/glb/tree.glb",
    zoom: 0.3,
    rotX: 65,
    rotY: 45,
  },
  {
    id: "saucer",
    label: "Flying saucer",
    category: "Vehicles",
    kind: "glb",
    url: "/gallery/glb/poly-pizza/flying-saucer.glb",
    galleryBucket: "Textured",
    zoom: 0.2,
    rotX: 67,
    rotY: 42.3,
    attribution: GOOGLE_POLY_FLYING_SAUCER_ATTRIBUTION,
  },
  {
    id: "wheelbarrow",
    label: "Wheelbarrow",
    category: "Objects",
    kind: "obj",
    url: "/gallery/obj/wheelbarrow.obj",
    mtlUrl: "/gallery/obj/wheelbarrow.mtl",
    zoom: 0.2,
    rotX: 66.2,
    rotY: 36.1,
  },
  {
    id: "teapot",
    label: "Teapot",
    category: "Objects",
    kind: "obj",
    url: "/gallery/obj/teapot.obj",
    zoom: 0.2,
    rotX: 65,
    rotY: 45,
    attribution: UTAH_TEAPOT_ATTRIBUTION,
  },
  {
    id: "castle",
    label: "Castle",
    category: "Architecture",
    kind: "obj",
    url: "/gallery/obj/castle.obj",
    zoom: 0.15,
    rotX: 66.9,
    rotY: 68.5,
    attribution: KENNEY_MINIGOLF_ATTRIBUTION,
  },
  {
    id: "coliseum",
    label: "Coliseum",
    category: "Architecture",
    kind: "obj",
    url: "/gallery/obj/coliseum.obj",
    zoom: 0.15,
    rotX: 65,
    rotY: 45,
  },
  ...OBJ_PRESET_FILES.map(objPreset),
  ...GLB_PRESET_FILES.map(glbPreset),
  ...POLY_PIZZA_PRESET_FILES.map(glbPreset),
  ...VOX_PRESET_FILES.map(voxPreset),
];
