export { axesHelperPolygons } from "./axesPolygons";
export type { AxesHelperOptions } from "./axesPolygons";
export { arrowPolygons } from "./arrowPolygons";
export type { ArrowPolygonsOptions } from "./arrowPolygons";
export { ringPolygons } from "./ringPolygons";
export type { RingPolygonsOptions } from "./ringPolygons";
export { ringQuadPolygons } from "./ringQuadPolygons";
export type { RingQuadPolygonsOptions } from "./ringQuadPolygons";
export { planePolygons } from "./planePolygons";
export type { PlanePolygonsOptions } from "./planePolygons";
export { octahedronPolygons } from "./octahedronPolygons";
export type { OctahedronPolygonsOptions } from "./octahedronPolygons";
export { tetrahedronPolygons } from "./tetrahedronPolygons";
export type { TetrahedronPolygonsOptions } from "./tetrahedronPolygons";
export { cubePolygons } from "./cubePolygons";
export type { CubePolygonsOptions } from "./cubePolygons";
export { dodecahedronPolygons } from "./dodecahedronPolygons";
export type { DodecahedronPolygonsOptions } from "./dodecahedronPolygons";
export { icosahedronPolygons } from "./icosahedronPolygons";
export type { IcosahedronPolygonsOptions } from "./icosahedronPolygons";
export { spherePolygons } from "./spherePolygons";
export type { SpherePolygonsOptions } from "./spherePolygons";
export { cylinderPolygons } from "./cylinderPolygons";
export type { CylinderPolygonsOptions } from "./cylinderPolygons";
export { conePolygons } from "./conePolygons";
export type { ConePolygonsOptions } from "./conePolygons";
export { torusPolygons } from "./torusPolygons";
export type { TorusPolygonsOptions } from "./torusPolygons";
export { pyramidPolygons } from "./pyramidPolygons";
export type { PyramidPolygonsOptions } from "./pyramidPolygons";
