export { axesHelperPolygons } from "./axesPolygons";
export type { AxesHelperOptions } from "./axesPolygons";
export { arrowPolygons } from "./arrowPolygons";
export type { ArrowPolygonsOptions } from "./arrowPolygons";
export { ringPolygons } from "./ringPolygons";
export type { RingPolygonsOptions } from "./ringPolygons";
export { ringQuadPolygons } from "./ringQuadPolygons";
export type { RingQuadPolygonsOptions } from "./ringQuadPolygons";
export { planePolygons } from "./planePolygons";
export type { PlanePolygonsOptions } from "./planePolygons";
export { octahedronPolygons } from "./octahedronPolygons";
export type { OctahedronPolygonsOptions } from "./octahedronPolygons";
export { tetrahedronPolygons } from "./tetrahedronPolygons";
export type { TetrahedronPolygonsOptions } from "./tetrahedronPolygons";
export { cubePolygons } from "./cubePolygons";
export type { CubePolygonsOptions } from "./cubePolygons";
export { dodecahedronPolygons } from "./dodecahedronPolygons";
export type { DodecahedronPolygonsOptions } from "./dodecahedronPolygons";
export { icosahedronPolygons } from "./icosahedronPolygons";
export type { IcosahedronPolygonsOptions } from "./icosahedronPolygons";
export { spherePolygons } from "./spherePolygons";
export type { SpherePolygonsOptions } from "./spherePolygons";
export { cylinderPolygons } from "./cylinderPolygons";
export type { CylinderPolygonsOptions } from "./cylinderPolygons";
export { conePolygons } from "./conePolygons";
export type { ConePolygonsOptions } from "./conePolygons";
export { torusPolygons } from "./torusPolygons";
export type { TorusPolygonsOptions } from "./torusPolygons";
export { pyramidPolygons } from "./pyramidPolygons";
export type { PyramidPolygonsOptions } from "./pyramidPolygons";
export { prismPolygons } from "./prismPolygons";
export type { PrismPolygonsOptions } from "./prismPolygons";
export { antiprismPolygons } from "./antiprismPolygons";
export type { AntiprismPolygonsOptions } from "./antiprismPolygons";
export { bipyramidPolygons } from "./bipyramidPolygons";
export type { BipyramidPolygonsOptions } from "./bipyramidPolygons";
export { trapezohedronPolygons } from "./trapezohedronPolygons";
export type { TrapezohedronPolygonsOptions } from "./trapezohedronPolygons";
export { smallStellatedDodecahedronPolygons } from "./smallStellatedDodecahedronPolygons";
export type { SmallStellatedDodecahedronPolygonsOptions } from "./smallStellatedDodecahedronPolygons";
export { greatDodecahedronPolygons } from "./greatDodecahedronPolygons";
export type { GreatDodecahedronPolygonsOptions } from "./greatDodecahedronPolygons";
export { greatStellatedDodecahedronPolygons } from "./greatStellatedDodecahedronPolygons";
export type { GreatStellatedDodecahedronPolygonsOptions } from "./greatStellatedDodecahedronPolygons";
export { greatIcosahedronPolygons } from "./greatIcosahedronPolygons";
export type { GreatIcosahedronPolygonsOptions } from "./greatIcosahedronPolygons";
export { cuboctahedronPolygons } from "./cuboctahedronPolygons";
export type { CuboctahedronPolygonsOptions } from "./cuboctahedronPolygons";
export { icosidodecahedronPolygons } from "./icosidodecahedronPolygons";
export type { IcosidodecahedronPolygonsOptions } from "./icosidodecahedronPolygons";
export { truncatedTetrahedronPolygons } from "./truncatedTetrahedronPolygons";
export type { TruncatedTetrahedronPolygonsOptions } from "./truncatedTetrahedronPolygons";
export { truncatedCubePolygons } from "./truncatedCubePolygons";
export type { TruncatedCubePolygonsOptions } from "./truncatedCubePolygons";
export { truncatedOctahedronPolygons } from "./truncatedOctahedronPolygons";
export type { TruncatedOctahedronPolygonsOptions } from "./truncatedOctahedronPolygons";
export { truncatedDodecahedronPolygons } from "./truncatedDodecahedronPolygons";
export type { TruncatedDodecahedronPolygonsOptions } from "./truncatedDodecahedronPolygons";
export { truncatedIcosahedronPolygons } from "./truncatedIcosahedronPolygons";
export type { TruncatedIcosahedronPolygonsOptions } from "./truncatedIcosahedronPolygons";
export { truncatedCuboctahedronPolygons } from "./truncatedCuboctahedronPolygons";
export type { TruncatedCuboctahedronPolygonsOptions } from "./truncatedCuboctahedronPolygons";
export { truncatedIcosidodecahedronPolygons } from "./truncatedIcosidodecahedronPolygons";
export type { TruncatedIcosidodecahedronPolygonsOptions } from "./truncatedIcosidodecahedronPolygons";
export { rhombicuboctahedronPolygons } from "./rhombicuboctahedronPolygons";
export type { RhombicuboctahedronPolygonsOptions } from "./rhombicuboctahedronPolygons";
export { rhombicosidodecahedronPolygons } from "./rhombicosidodecahedronPolygons";
export type { RhombicosidodecahedronPolygonsOptions } from "./rhombicosidodecahedronPolygons";
export { snubCubePolygons } from "./snubCubePolygons";
export type { SnubCubePolygonsOptions } from "./snubCubePolygons";
export { snubDodecahedronPolygons } from "./snubDodecahedronPolygons";
export type { SnubDodecahedronPolygonsOptions } from "./snubDodecahedronPolygons";
