// @layoutit/polycss-react — React bindings for the glyphcss ASCII paint backend.
//
// Public exports define the supported React package surface. Anything not
// exported here is an implementation detail.

// ── Animation (shared core; re-used by Glyphcss bindings) ──────────────────
export { usePolyAnimation } from "./animation/usePolyAnimation";
export type { UsePolyAnimationResult } from "./animation/usePolyAnimation";

// ── Re-exports from @layoutit/polycss-core for convenience ──────────────────
export type {
  Vec2,
  Vec3,
  Polygon,
  PolyDirectionalLight,
  PolyAmbientLight,
  ParseAnimationClip,
  ParseAnimationController,
  ParseResult,
  PolyAnimationClip,
  PolyAnimationAction,
  PolyAnimationMixer,
  PolyAnimationTarget,
  LoopMode,
  ObjParseOptions,
  GltfParseOptions,
  MtlParseResult,
  NormalizeResult,
  ParsedColor,
  TextureTriangle,
  PolygonFace,
  SceneBbox,
  SceneContext,
  SceneContextBuildArgs,
  SceneContextBuildResult,
  CameraState,
  CameraHandle,
  CameraStyleInput,
  AutoRotateOption,
  AutoRotateConfig,
  AxesHelperOptions,
  ArrowPolygonsOptions,
  RingPolygonsOptions,
  OctahedronPolygonsOptions,
  LoadMeshOptions,
  VoxParseOptions,
  SolidTextureSampleOptions,
  CoverPlanarPolygonsOptions,
  CullInteriorOptions,
  CameraCullNormalGroup,
  CameraCullRotation,
  ApproximateMergeOptions,
  OptimizeMeshPolygonsOptions,
} from "@layoutit/polycss-core";
export {
  CAMERA_BACKFACE_CULL_EPS,
  VOXEL_CAMERA_CULL_AXIS_EPS,
  VOXEL_CAMERA_CULL_NORMAL_LIMIT,
  normalizePolygons,
  mergePolygons,
  coverPlanarPolygons,
  optimizeMeshPolygons,
  cullInteriorPolygons,
  cameraCullNormalGroups,
  cameraCullNormalGroupsFromPolygons,
  cameraCullNormalKey,
  cameraCullVisibleSignature,
  cameraFacingDepth,
  isAxisAlignedSurfaceNormal,
  isVoxelCameraCullableNormalGroups,
  normalFacesCamera,
  polygonCssSurfaceNormal,
  polygonFacesCamera,
  parseObj,
  parseMtl,
  parseGltf,
  bakeSolidTextureSamples,
  bakeSolidTextureSampledPolygons,
  loadMesh,
  createIsometricCamera,
  parseVox,
  polygonFaces,
  computeShapeLighting,
  parseColor,
  parsePureColor,
  parseHexColor,
  parseRgbColor,
  formatColor,
  clampChannel,
  shadeColor,
  rotateVec3,
  inverseRotateVec3,
  axesHelperPolygons,
  arrowPolygons,
  ringPolygons,
  octahedronPolygons,
  buildSceneContext,
  computeSceneBbox,
  BASE_TILE,
  DEFAULT_CAMERA_STATE,
  DEFAULT_PROJECTION,
  normalizeInvertMultiplier,
  createPolyAnimationMixer,
  LoopOnce,
  LoopRepeat,
  LoopPingPong,
} from "@layoutit/polycss-core";

// ── Glyphcss (ASCII paint backend) bindings ─────────────────────────────────
export {
  GlyphcssScene,
  GlyphcssMesh,
  GlyphcssHotspot,
  GlyphcssSceneContext,
  useGlyphcssSceneContext,
  useGlyphcssMesh,
  findGlyphcssMeshHandle,
  GlyphcssCamera,
  GlyphcssPerspectiveCamera,
  GlyphcssOrthographicCamera,
  GlyphcssCameraContext,
  useGlyphcssCamera,
  GlyphcssOrbitControls,
  GlyphcssMapControls,
  GlyphcssFirstPersonControls,
  GlyphcssAxesHelper,
  GlyphcssDirectionalLightHelper,
  injectGlyphcssBaseStyles,
  useGlyphcssAnimation,
} from "./glyphcss";
export type {
  GlyphcssSceneProps,
  GlyphcssMeshProps,
  GlyphcssHotspotProps,
  GlyphcssSceneContextValue,
  UseGlyphcssMeshResult,
  UseGlyphcssMeshOptions,
  GlyphcssCameraProps,
  GlyphcssPerspectiveCameraProps,
  GlyphcssOrthographicCameraProps,
  GlyphcssCameraContextValue,
  GlyphcssOrbitControlsProps,
  GlyphcssMapControlsProps,
  GlyphcssFirstPersonControlsProps,
  GlyphcssAxesHelperProps,
  GlyphcssDirectionalLightHelperProps,
  UseGlyphcssAnimationResult,
} from "./glyphcss";
