// @glyphcss/react — React bindings for the glyphcss ASCII paint backend.
//
// Public exports define the supported React package surface. Anything not
// exported here is an implementation detail.

// ── Re-exports from @glyphcss/core for convenience ──────────────────────────
export type {
  Vec2,
  Vec3,
  Polygon,
  GlyphDirectionalLight,
  GlyphAmbientLight,
  ParseAnimationClip,
  ParseAnimationController,
  ParseResult,
  GlyphAnimationClip,
  GlyphAnimationAction,
  GlyphAnimationMixer,
  GlyphAnimationTarget,
  LoopMode,
  ObjParseOptions,
  GltfParseOptions,
  MtlParseResult,
  NormalizeResult,
  ParsedColor,
  TextureTriangle,
  PolygonFace,
  SceneBbox,
  SceneContext,
  SceneContextBuildArgs,
  SceneContextBuildResult,
  CameraState,
  CameraHandle,
  CameraStyleInput,
  AutoRotateOption,
  AutoRotateConfig,
  AxesHelperOptions,
  ArrowPolygonsOptions,
  RingPolygonsOptions,
  OctahedronPolygonsOptions,
  LoadMeshOptions,
  VoxParseOptions,
  SolidTextureSampleOptions,
  CoverPlanarPolygonsOptions,
  CullInteriorOptions,
  CameraCullNormalGroup,
  CameraCullRotation,
  ApproximateMergeOptions,
  OptimizeMeshPolygonsOptions,
  GlyphGeometryName,
  GlyphGeometryOptions,
} from "@glyphcss/core";
export {
  CAMERA_BACKFACE_CULL_EPS,
  VOXEL_CAMERA_CULL_AXIS_EPS,
  VOXEL_CAMERA_CULL_NORMAL_LIMIT,
  normalizePolygons,
  mergePolygons,
  coverPlanarPolygons,
  optimizeMeshPolygons,
  cullInteriorPolygons,
  cameraCullNormalGroups,
  cameraCullNormalGroupsFromPolygons,
  cameraCullNormalKey,
  cameraCullVisibleSignature,
  cameraFacingDepth,
  isAxisAlignedSurfaceNormal,
  isVoxelCameraCullableNormalGroups,
  normalFacesCamera,
  polygonCssSurfaceNormal,
  polygonFacesCamera,
  parseObj,
  parseMtl,
  parseGltf,
  bakeSolidTextureSamples,
  bakeSolidTextureSampledPolygons,
  loadMesh,
  createIsometricCamera,
  parseVox,
  polygonFaces,
  computeShapeLighting,
  parseColor,
  parsePureColor,
  parseHexColor,
  parseRgbColor,
  formatColor,
  clampChannel,
  shadeColor,
  rotateVec3,
  inverseRotateVec3,
  resolveGeometry,
  tetrahedronPolygons,
  cubePolygons,
  octahedronPolygons,
  dodecahedronPolygons,
  icosahedronPolygons,
  smallStellatedDodecahedronPolygons,
  greatDodecahedronPolygons,
  greatStellatedDodecahedronPolygons,
  greatIcosahedronPolygons,
  cuboctahedronPolygons,
  icosidodecahedronPolygons,
  truncatedTetrahedronPolygons,
  truncatedCubePolygons,
  truncatedOctahedronPolygons,
  truncatedDodecahedronPolygons,
  truncatedIcosahedronPolygons,
  truncatedCuboctahedronPolygons,
  truncatedIcosidodecahedronPolygons,
  rhombicuboctahedronPolygons,
  rhombicosidodecahedronPolygons,
  snubCubePolygons,
  snubDodecahedronPolygons,
  rhombicDodecahedronPolygons,
  rhombicTriacontahedronPolygons,
  triakisTetrahedronPolygons,
  triakisOctahedronPolygons,
  triakisIcosahedronPolygons,
  tetrakisHexahedronPolygons,
  pentakisDodecahedronPolygons,
  disdyakisDodecahedronPolygons,
  disdyakisTriacontahedronPolygons,
  deltoidalIcositetrahedronPolygons,
  deltoidalHexecontahedronPolygons,
  pentagonalIcositetrahedronPolygons,
  pentagonalHexecontahedronPolygons,
  prismPolygons,
  antiprismPolygons,
  bipyramidPolygons,
  trapezohedronPolygons,
  spherePolygons,
  cylinderPolygons,
  conePolygons,
  torusPolygons,
  pyramidPolygons,
  planePolygons,
  ringPolygons,
  ringQuadPolygons,
  arrowPolygons,
  axesHelperPolygons,
  buildSceneContext,
  computeSceneBbox,
  BASE_TILE,
  DEFAULT_CAMERA_STATE,
  DEFAULT_PROJECTION,
  normalizeInvertMultiplier,
  createGlyphAnimationMixer,
  LoopOnce,
  LoopRepeat,
  LoopPingPong,
} from "@glyphcss/core";

// ── Glyphcss (ASCII paint backend) bindings ─────────────────────────────────
export {
  GlyphScene,
  GlyphMesh,
  GlyphGround,
  GlyphHotspot,
  GlyphSceneContext,
  useGlyphSceneContext,
  useGlyphMesh,
  findGlyphMeshHandle,
  pointInMeshElement,
  findMeshUnderPoint,
  GlyphCamera,
  GlyphPerspectiveCamera,
  GlyphOrthographicCamera,
  GlyphCameraContext,
  useGlyphCamera,
  GlyphOrbitControls,
  GlyphMapControls,
  GlyphFirstPersonControls,
  GlyphAxesHelper,
  GlyphDirectionalLightHelper,
  injectGlyphBaseStyles,
  useGlyphAnimation,
} from "./glyphcss";
export type {
  GlyphSceneProps,
  GlyphMeshProps,
  GlyphGroundProps,
  GlyphHotspotProps,
  GlyphSceneContextValue,
  UseGlyphMeshResult,
  UseGlyphMeshOptions,
  GlyphCameraProps,
  GlyphPerspectiveCameraProps,
  GlyphOrthographicCameraProps,
  GlyphCameraContextValue,
  GlyphOrbitControlsProps,
  GlyphMapControlsProps,
  GlyphFirstPersonControlsProps,
  GlyphAxesHelperProps,
  GlyphDirectionalLightHelperProps,
  UseGlyphAnimationResult,
} from "./glyphcss";

// ── Mesh handle type ──────────────────────────────────────────────────────────
export type { GlyphMeshHandle } from "glyphcss";

// ── Event types ───────────────────────────────────────────────────────────────
export type {
  GlyphPointerEvent,
  GlyphMouseEvent,
  GlyphWheelEvent,
  GlyphEventHandler,
} from "glyphcss";
