// ── Re-exports from @glyphcss/core ─────────────────────────────────────────
export type {
  Polygon,
  Vec2,
  Vec3,
  GlyphDirectionalLight,
  GlyphAmbientLight,
  ParseResult,
  ParseAnimationClip,
  ParseAnimationController,
  GlyphAnimationClip,
  GlyphAnimationAction,
  GlyphAnimationMixer,
  GlyphAnimationTarget,
  LoopMode,
  ObjParseOptions,
  GltfParseOptions,
  MtlParseResult,
  NormalizeResult,
  ParsedColor,
  TextureTriangle,
  PolygonFace,
  SceneBbox,
  SceneContext,
  SceneContextBuildArgs,
  SceneContextBuildResult,
  CameraState,
  CameraHandle,
  CameraStyleInput,
  AutoRotateOption,
  AutoRotateConfig,
  AxesHelperOptions,
  ArrowPolygonsOptions,
  RingPolygonsOptions,
  OctahedronPolygonsOptions,
  LoadMeshOptions,
  VoxParseOptions,
  SolidTextureSampleOptions,
  CoverPlanarPolygonsOptions,
  CullInteriorOptions,
  CameraCullNormalGroup,
  CameraCullRotation,
  ApproximateMergeOptions,
  OptimizeMeshPolygonsOptions,
  GlyphGeometryName,
  GlyphGeometryOptions,
} from "@glyphcss/core";
export {
  CAMERA_BACKFACE_CULL_EPS,
  VOXEL_CAMERA_CULL_AXIS_EPS,
  VOXEL_CAMERA_CULL_NORMAL_LIMIT,
  normalizePolygons,
  mergePolygons,
  coverPlanarPolygons,
  optimizeMeshPolygons,
  cullInteriorPolygons,
  cameraCullNormalGroups,
  cameraCullNormalGroupsFromPolygons,
  cameraCullNormalKey,
  cameraCullVisibleSignature,
  cameraFacingDepth,
  isAxisAlignedSurfaceNormal,
  isVoxelCameraCullableNormalGroups,
  normalFacesCamera,
  polygonCssSurfaceNormal,
  polygonFacesCamera,
  parseObj,
  parseMtl,
  parseGltf,
  bakeSolidTextureSamples,
  bakeSolidTextureSampledPolygons,
  loadMesh,
  createIsometricCamera,
  parseStl,
  parseVox,
  polygonFaces,
  computeShapeLighting,
  parseColor,
  parsePureColor,
  parseHexColor,
  parseRgbColor,
  formatColor,
  clampChannel,
  shadeColor,
  rotateVec3,
  inverseRotateVec3,
  resolveGeometry,
  tetrahedronPolygons,
  cubePolygons,
  octahedronPolygons,
  dodecahedronPolygons,
  icosahedronPolygons,
  smallStellatedDodecahedronPolygons,
  greatDodecahedronPolygons,
  greatStellatedDodecahedronPolygons,
  greatIcosahedronPolygons,
  cuboctahedronPolygons,
  icosidodecahedronPolygons,
  truncatedTetrahedronPolygons,
  truncatedCubePolygons,
  truncatedOctahedronPolygons,
  truncatedDodecahedronPolygons,
  truncatedIcosahedronPolygons,
  truncatedCuboctahedronPolygons,
  truncatedIcosidodecahedronPolygons,
  rhombicuboctahedronPolygons,
  rhombicosidodecahedronPolygons,
  snubCubePolygons,
  snubDodecahedronPolygons,
  rhombicDodecahedronPolygons,
  rhombicTriacontahedronPolygons,
  triakisTetrahedronPolygons,
  triakisOctahedronPolygons,
  triakisIcosahedronPolygons,
  tetrakisHexahedronPolygons,
  pentakisDodecahedronPolygons,
  disdyakisDodecahedronPolygons,
  disdyakisTriacontahedronPolygons,
  deltoidalIcositetrahedronPolygons,
  deltoidalHexecontahedronPolygons,
  pentagonalIcositetrahedronPolygons,
  pentagonalHexecontahedronPolygons,
  prismPolygons,
  antiprismPolygons,
  bipyramidPolygons,
  trapezohedronPolygons,
  spherePolygons,
  cylinderPolygons,
  conePolygons,
  torusPolygons,
  pyramidPolygons,
  planePolygons,
  ringPolygons,
  ringQuadPolygons,
  arrowPolygons,
  axesHelperPolygons,
  buildSceneContext,
  computeSceneBbox,
  BASE_TILE,
  DEFAULT_CAMERA_STATE,
  DEFAULT_PROJECTION,
  normalizeInvertMultiplier,
  createGlyphAnimationMixer,
  LoopOnce,
  LoopRepeat,
  LoopPingPong,
} from "@glyphcss/core";

// ── Glyphcss (ASCII paint backend) bindings ─────────────────────────────────
export {
  GlyphScene,
  GlyphSceneStatic,
  GlyphMesh,
  GlyphEffectLayer,
  GlyphGround,
  GlyphHotspot,
  GlyphSceneContextKey,
  useGlyphMesh,
  useGlyphSceneContext,
  findGlyphMeshHandle,
  pointInMeshElement,
  findMeshUnderPoint,
  GlyphCamera,
  GlyphPerspectiveCamera,
  GlyphOrthographicCamera,
  GlyphCameraContextKey,
  useGlyphCamera,
  GlyphOrbitControls,
  GlyphMapControls,
  GlyphFirstPersonControls,
  GlyphAxesHelper,
  GlyphDirectionalLightHelper,
  injectGlyphBaseStyles,
  useGlyphAnimation,
} from "./glyphcss";
export type {
  GlyphSceneProps,
  GlyphSceneStaticProps,
  GlyphMeshProps,
  GlyphEffectLayerComponent,
  GlyphEffectLayerExposed,
  GlyphEffectLayerProps,
  GlyphGroundProps,
  GlyphHotspotProps,
  GlyphSceneContextValue,
  GlyphCameraProps,
  GlyphPerspectiveCameraProps,
  GlyphOrthographicCameraProps,
  GlyphCameraContextValue,
  GlyphOrbitControlsProps,
  GlyphMapControlsProps,
  GlyphFirstPersonControlsProps,
  GlyphAxesHelperProps,
  GlyphDirectionalLightHelperProps,
  UseGlyphAnimationResult,
  UseGlyphMeshOptions,
  UseGlyphMeshResult,
} from "./glyphcss";

// ── Mesh handle type ──────────────────────────────────────────────────────────
export type { GlyphMeshHandle } from "glyphcss";

// ── Cell-effect layer types ──────────────────────────────────────────────────
export type {
  GlyphEffectLayerHandle,
  GlyphEffectTarget,
  GlyphEffectBlend,
} from "glyphcss";

export { createGlyphSurfaceAtlasWebGpuSession, reprojectGlyphSurfaceAtlas, resampleGlyphTemporalInputs } from "glyphcss";
export type {
  GlyphSurfaceAtlasState,
  GlyphSurfaceAtlasProvenance,
  GlyphSurfaceAtlasCamera,
  GlyphSurfaceAtlasSurface,
  GlyphReprojectSurfaceAtlasOptions,
  GlyphReprojectSurfaceAtlasResult,
  GlyphSurfaceAtlasWebGpuSession,
  GlyphSurfaceAtlasWebGpuSessionOptions,
  GlyphSurfaceAtlasWebGpuSubmitOptions,
  GlyphSurfaceAtlasWebGpuReadback,
  GlyphSurfaceAtlasWebGpuPresentationReadback,
  GlyphSurfaceAtlasWebGpuProfile,
} from "glyphcss";

export { GLYPH_CONTROL_TENSOR_CONTRACT, packGlyphControlTensor, validateGlyphControlTensorSpec } from "glyphcss";
export type {
  GlyphControlTensorChannelSource,
  GlyphControlTensorChannel,
  GlyphControlTensorContract,
  GlyphControlTensorInstance,
  GlyphControlTensorSpec,
  GlyphControlTensorNormalization,
  GlyphTemporalControlInputs,
  GlyphPackedControlTensors,
} from "glyphcss";

// ── Shadow options ────────────────────────────────────────────────────────────
export type { GlyphShadowOptions } from "glyphcss";

// ── Pure control-frame capture ───────────────────────────────────────────────
export { buildGlyphControlFrame, computeGlyphControlContentSha256, computeGlyphControlGeometryHashes, resolveGlyphControlLineage, validateGlyphControlMetadata } from "glyphcss";
export type {
  GlyphObjectDictionary,
  GlyphObjectDictionaryClass,
  GlyphControlSceneManifest,
  GlyphControlInstance,
  GlyphControlSurface,
  GlyphControlFrameOptions,
  GlyphControlFrameMetadata,
  GlyphControlCameraMetadata,
  GlyphControlFrame,
  GlyphControlGeometryHashes,
  GlyphControlPolygonLineage,
} from "glyphcss";

// ── Cell-buffer contract + post-rasterize hook (M4 composition effects) ───────
export { rasterizeToCells, buildCellGrid, applyCellHook } from "glyphcss";
export type { CellGrid, TransformCells } from "glyphcss";

// ── Event types ───────────────────────────────────────────────────────────────
export type {
  GlyphPointerEvent,
  GlyphMouseEvent,
  GlyphWheelEvent,
  GlyphEventHandler,
} from "glyphcss";
