// ── Re-exports from @glyphcss/core ─────────────────────────────────────────
export type {
  Polygon,
  Vec2,
  Vec3,
  GlyphcssDirectionalLight,
  GlyphcssAmbientLight,
  ParseResult,
  ParseAnimationClip,
  ParseAnimationController,
  GlyphcssAnimationClip,
  GlyphcssAnimationAction,
  GlyphcssAnimationMixer,
  GlyphcssAnimationTarget,
  LoopMode,
  ObjParseOptions,
  GltfParseOptions,
  MtlParseResult,
  NormalizeResult,
  ParsedColor,
  TextureTriangle,
  PolygonFace,
  SceneBbox,
  SceneContext,
  SceneContextBuildArgs,
  SceneContextBuildResult,
  CameraState,
  CameraHandle,
  CameraStyleInput,
  AutoRotateOption,
  AutoRotateConfig,
  AxesHelperOptions,
  ArrowPolygonsOptions,
  RingPolygonsOptions,
  OctahedronPolygonsOptions,
  LoadMeshOptions,
  VoxParseOptions,
  SolidTextureSampleOptions,
  CoverPlanarPolygonsOptions,
  CullInteriorOptions,
  CameraCullNormalGroup,
  CameraCullRotation,
  ApproximateMergeOptions,
  OptimizeMeshPolygonsOptions,
} from "@glyphcss/core";
export {
  CAMERA_BACKFACE_CULL_EPS,
  VOXEL_CAMERA_CULL_AXIS_EPS,
  VOXEL_CAMERA_CULL_NORMAL_LIMIT,
  normalizePolygons,
  mergePolygons,
  coverPlanarPolygons,
  optimizeMeshPolygons,
  cullInteriorPolygons,
  cameraCullNormalGroups,
  cameraCullNormalGroupsFromPolygons,
  cameraCullNormalKey,
  cameraCullVisibleSignature,
  cameraFacingDepth,
  isAxisAlignedSurfaceNormal,
  isVoxelCameraCullableNormalGroups,
  normalFacesCamera,
  polygonCssSurfaceNormal,
  polygonFacesCamera,
  parseObj,
  parseMtl,
  parseGltf,
  bakeSolidTextureSamples,
  bakeSolidTextureSampledPolygons,
  loadMesh,
  createIsometricCamera,
  parseVox,
  polygonFaces,
  computeShapeLighting,
  parseColor,
  parsePureColor,
  parseHexColor,
  parseRgbColor,
  formatColor,
  clampChannel,
  shadeColor,
  rotateVec3,
  inverseRotateVec3,
  axesHelperPolygons,
  arrowPolygons,
  ringPolygons,
  octahedronPolygons,
  buildSceneContext,
  computeSceneBbox,
  BASE_TILE,
  DEFAULT_CAMERA_STATE,
  DEFAULT_PROJECTION,
  normalizeInvertMultiplier,
  createGlyphcssAnimationMixer,
  LoopOnce,
  LoopRepeat,
  LoopPingPong,
} from "@glyphcss/core";

// ── Glyphcss (ASCII paint backend) bindings ─────────────────────────────────
export {
  GlyphcssScene,
  GlyphcssMesh,
  GlyphcssGround,
  GlyphcssHotspot,
  GlyphcssSceneContextKey,
  useGlyphcssSceneContext,
  findGlyphcssMeshHandle,
  pointInMeshElement,
  findMeshUnderPoint,
  GlyphcssCamera,
  GlyphcssPerspectiveCamera,
  GlyphcssOrthographicCamera,
  GlyphcssCameraContextKey,
  useGlyphcssCamera,
  GlyphcssOrbitControls,
  GlyphcssMapControls,
  GlyphcssFirstPersonControls,
  GlyphcssAxesHelper,
  GlyphcssDirectionalLightHelper,
  injectGlyphcssBaseStyles,
  useGlyphcssAnimation,
} from "./glyphcss";
export type {
  GlyphcssSceneProps,
  GlyphcssMeshProps,
  GlyphcssGroundProps,
  GlyphcssHotspotProps,
  GlyphcssSceneContextValue,
  GlyphcssCameraProps,
  GlyphcssPerspectiveCameraProps,
  GlyphcssOrthographicCameraProps,
  GlyphcssCameraContextValue,
  GlyphcssOrbitControlsProps,
  GlyphcssMapControlsProps,
  GlyphcssFirstPersonControlsProps,
  GlyphcssAxesHelperProps,
  GlyphcssDirectionalLightHelperProps,
  UseGlyphcssAnimationResultVue,
} from "./glyphcss";

// ── Mesh handle type ──────────────────────────────────────────────────────────
export type { GlyphcssMeshHandle } from "glyphcss";

// ── Event types ───────────────────────────────────────────────────────────────
export type {
  GlyphcssPointerEvent,
  GlyphcssMouseEvent,
  GlyphcssWheelEvent,
  GlyphcssEventHandler,
} from "glyphcss";
