/**
 * Byte-parity test: glyphcss's rasterize() must produce byte-identical output
 * to asciss's rasterize() for the same input.
 *
 * Only solid mode is tested — wireframe uses Math.random() for glyph selection
 * and cannot be deterministically byte-compared. Algorithm bytes are unchanged
 * since rasterize.ts was copied verbatim from asciss (only import path updated).
 *
 * Fixtures were generated by /tmp/gen-asciss-fixtures.mjs using asciss's own
 * rasterize() with fixed camera+grid+mode+lights parameters.
 */
/**
 * Byte-parity test: glyphcss's rasterize() must produce byte-identical output
 * to asciss's rasterize() for the same input.
 *
 * Only solid mode is tested — wireframe uses Math.random() for glyph selection
 * and cannot be deterministically byte-compared. Algorithm bytes are unchanged
 * since rasterize.ts was copied verbatim from asciss (only import path updated).
 *
 * Fixtures were generated by /tmp/gen-asciss-fixtures.mjs using asciss's own
 * rasterize() with fixed camera+grid+mode+lights parameters.
 *
 * Triangle inputs (N=3 polygons) fan-triangulate to exactly one triangle each.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { resolve } from "path";
import { rasterize } from "../src/render/rasterize";
import { buildRasterizeContext } from "../src/api/rasterizeContext";
import { createGlyphPerspectiveCamera } from "../src/api/createGlyphCamera";
import type { Polygon, Vec3 } from "@glyphcss/core";

const FIXTURE_DIR = resolve(__dirname, "fixtures");

const GRID = { cols: 40, rows: 20, cellAspect: 2.0 };
const DIR_LIGHT = { direction: [0.5, 0.7, 0.5] as Vec3, intensity: 1 };
const AMB_LIGHT = { intensity: 0.4 };

function loadFixture(name: string): string {
  return readFileSync(resolve(FIXTURE_DIR, `${name}.txt`), "utf8");
}

function makeUnitCubePolygons(): Polygon[] {
  const faces: Array<[Vec3, Vec3, Vec3, string]> = [
    [[-1,-1, 1],[1,-1, 1],[1, 1, 1],"#ff4444"],
    [[-1,-1, 1],[1, 1, 1],[-1, 1, 1],"#ff4444"],
    [[1,-1,-1],[-1,-1,-1],[-1, 1,-1],"#44ff44"],
    [[1,-1,-1],[-1, 1,-1],[1, 1,-1],"#44ff44"],
    [[-1, 1, 1],[1, 1, 1],[1, 1,-1],"#4444ff"],
    [[-1, 1, 1],[1, 1,-1],[-1, 1,-1],"#4444ff"],
    [[-1,-1,-1],[1,-1,-1],[1,-1, 1],"#ffff44"],
    [[-1,-1,-1],[1,-1, 1],[-1,-1, 1],"#ffff44"],
    [[1,-1, 1],[1,-1,-1],[1, 1,-1],"#44ffff"],
    [[1,-1, 1],[1, 1,-1],[1, 1, 1],"#44ffff"],
    [[-1,-1,-1],[-1,-1, 1],[-1, 1, 1],"#ff44ff"],
    [[-1,-1,-1],[-1, 1, 1],[-1, 1,-1],"#ff44ff"],
  ];
  return faces.map(([v0, v1, v2, color]) => ({ vertices: [v0, v1, v2], color }));
}

function makeSinglePolygon(): Polygon[] {
  return [{ vertices: [[0, 1, 0], [-1, -1, 0], [1, -1, 0]], color: "#aaaaaa" }];
}

function makeTetrahedronPolygons(): Polygon[] {
  const s = Math.sqrt(2/3);
  const r = Math.sqrt(1/3);
  const v: Vec3[] = [
    [0, 1, 0],
    [2*r, -1/3, 0],
    [-r, -1/3, s],
    [-r, -1/3, -s],
  ];
  return [
    { vertices: [v[0]!, v[1]!, v[2]!], color: "#ff6600" },
    { vertices: [v[0]!, v[2]!, v[3]!], color: "#0066ff" },
    { vertices: [v[0]!, v[3]!, v[1]!], color: "#00ff66" },
    { vertices: [v[1]!, v[3]!, v[2]!], color: "#ffff00" },
  ];
}

describe("parity: glyphcss rasterize vs asciss fixtures", () => {
  it("unit cube (solid, no colors) matches asciss output byte-for-byte", () => {
    const camera = createGlyphPerspectiveCamera({ rotX: 0.4, rotY: 0.5, zoom: 0.35 });
    const ctx = buildRasterizeContext({
      camera,
      grid: GRID,
      polygons: makeUnitCubePolygons(),
      mode: "solid",
      directionalLight: DIR_LIGHT,
      ambientLight: AMB_LIGHT,
      glyphPalette: "default",
      useColors: false,
    });
    const output = rasterize(ctx);
    const fixture = loadFixture("unit-cube");
    expect(output).toBe(fixture);
  });

  it("single triangle (solid, no colors) matches asciss output byte-for-byte", () => {
    const camera = createGlyphPerspectiveCamera({ rotX: 0.2, rotY: 0.3, zoom: 0.5 });
    const ctx = buildRasterizeContext({
      camera,
      grid: GRID,
      polygons: makeSinglePolygon(),
      mode: "solid",
      directionalLight: DIR_LIGHT,
      ambientLight: AMB_LIGHT,
      glyphPalette: "default",
      useColors: false,
    });
    const output = rasterize(ctx);
    const fixture = loadFixture("single-triangle");
    expect(output).toBe(fixture);
  });

  it("tetrahedron (solid, no colors) matches asciss output byte-for-byte", () => {
    const camera = createGlyphPerspectiveCamera({ rotX: 0.3, rotY: 0.8, zoom: 0.4 });
    const ctx = buildRasterizeContext({
      camera,
      grid: GRID,
      polygons: makeTetrahedronPolygons(),
      mode: "solid",
      directionalLight: DIR_LIGHT,
      ambientLight: AMB_LIGHT,
      glyphPalette: "default",
      useColors: false,
    });
    const output = rasterize(ctx);
    const fixture = loadFixture("tetrahedron");
    expect(output).toBe(fixture);
  });
});
