// Sphere (`parametric3d`) preset — a COMPUTED example (`glyphChart3dSphereGrid`,
// `@glyphcss/charts/3d`), never vendored data (`../LICENSES.md`'s own
// "computed, not vendored" entry). Coloured by a real spherical-harmonic
// value grid (l=2, m=0: `Y ~ 3cos^2(theta) - 1`, the classic "dz^2" orbital
// shape) rather than by z itself, so the colour band genuinely differs from
// the height-field surfaces' own "colour reads height" convention —
// `options.value` is exactly the 4th grid `glyphChartParametric3d` accepts
// for this.
import { glyphChart3dSphereGrid } from "@glyphcss/charts/3d";
import type { Chart3dParametricDataset } from "./types";

const { x, y, z } = glyphChart3dSphereGrid(1, 24, 36);
const value = z.map((row, r) =>
  row.map((_, c) => {
    const theta = (Math.PI * r) / (z.length - 1);
    return 3 * Math.cos(theta) ** 2 - 1; // l=2, m=0 real spherical harmonic (unnormalized)
  }),
);

export const sphereParametric3dDataset: Chart3dParametricDataset = {
  id: "sphere-parametric-3d",
  markType: "parametric3d",
  title: "Sphere (spherical harmonic Y₂₀)",
  description:
    "A unit sphere sampled on a latitude/longitude grid, coloured by the l=2, m=0 real spherical harmonic — a computed reference example, not vendored data.",
  source: {
    name: "Computed example (glyphcss)",
    url: "",
    licence: "N/A — generated by this repository's own math, not sourced data",
  },
  data: { x, y, z, value },
  options: {
    wrapU: true,
    axes: {
      x: { title: "x" },
      y: { title: "y" },
      z: { title: "z" },
    },
  },
};
