// Torus (`parametric3d`) preset — a COMPUTED example (`glyphChart3dTorusGrid`,
// `@glyphcss/charts/3d`), never vendored data. Coloured by z (the default,
// no `value` grid), so the colour band reads the tube's own minor-angle
// undulation.
import { glyphChart3dTorusGrid } from "@glyphcss/charts/3d";
import type { Chart3dParametricDataset } from "./types";

const { x, y, z } = glyphChart3dTorusGrid(1.4, 0.5, 24, 36);

export const torusParametric3dDataset: Chart3dParametricDataset = {
  id: "torus-parametric-3d",
  markType: "parametric3d",
  title: "Torus",
  description:
    "A torus (major radius 1.4, minor radius 0.5) sampled on a major/minor-angle grid — a computed reference example, not vendored data.",
  source: {
    name: "Computed example (glyphcss)",
    url: "",
    licence: "N/A — generated by this repository's own math, not sourced data",
  },
  data: { x, y, z },
  options: {
    wrapU: true,
    wrapV: true,
    axes: {
      x: { title: "x" },
      y: { title: "y" },
      z: { title: "z" },
    },
  },
};
