#!/usr/bin/env bash
set -euo pipefail

context="${GLYPHCSS_DOCKER_CONTEXT:-gpu-4090}"
data_root="${GLYPHCSS_ARTIFACT_ROOT:-/mnt/docker-data/glyphcss-ascii-image-generation}"
parity_run_id="${GLYPHCSS_WEBGPU_PARITY_RUN_ID:?GLYPHCSS_WEBGPU_PARITY_RUN_ID is required}"
run_id="${GLYPHCSS_WEBGPU_LIFECYCLE_RUN_ID:-webgpu-lifecycle-$(date -u +%Y%m%dT%H%M%SZ)}"
base_image="mcr.microsoft.com/playwright@sha256:6446946a1d9fd62d9ae501312a2d76a43ee688542b21622056a372959b65d63d"
parity_dir="$data_root/reference-browser/runs/$parity_run_id"
run_dir="$data_root/reference-browser/runs/$run_id"

metadata="$(docker --context "$context" run --rm --entrypoint node --volume "$data_root:/artifacts" "$base_image" -e 'const fs=require("fs"); const m=JSON.parse(fs.readFileSync(process.argv[1], "utf8")); process.stdout.write(JSON.stringify({ source:m.source, manifestSha256:require("crypto").createHash("sha256").update(fs.readFileSync(process.argv[1])).digest("hex") }));' "/artifacts/reference-browser/runs/$parity_run_id/run-manifest.json")"
image_id="$(printf '%s' "$metadata" | node -e 'let s=""; process.stdin.on("data", d => s += d).on("end", () => process.stdout.write(JSON.parse(s).source.imageId))')"
source_archive_sha256="$(printf '%s' "$metadata" | node -e 'let s=""; process.stdin.on("data", d => s += d).on("end", () => process.stdout.write(JSON.parse(s).source.archiveSha256))')"
source_file_set_sha256="$(printf '%s' "$metadata" | node -e 'let s=""; process.stdin.on("data", d => s += d).on("end", () => process.stdout.write(JSON.parse(s).source.fileSetSha256))')"
parity_manifest_sha256="$(printf '%s' "$metadata" | node -e 'let s=""; process.stdin.on("data", d => s += d).on("end", () => process.stdout.write(JSON.parse(s).manifestSha256))')"
[[ "$image_id" =~ ^sha256:[a-f0-9]{64}$ && "$source_archive_sha256" =~ ^[a-f0-9]{64}$ && "$source_file_set_sha256" =~ ^[a-f0-9]{64}$ && "$parity_manifest_sha256" =~ ^[a-f0-9]{64}$ ]]
docker --context "$context" image inspect "$image_id" >/dev/null
docker --context "$context" run --rm --user root --entrypoint bash --volume "$data_root:/artifacts" "$base_image" -lc "test ! -e '/artifacts/reference-browser/runs/$run_id'; install -d -m 0750 -o pwuser -g users '/artifacts/reference-browser/runs/$run_id'"
render_group="$(docker --context "$context" run --rm --gpus all --entrypoint bash "$image_id" -lc 'stat -c %g /dev/dri/renderD*')"
docker --context "$context" run --rm --gpus all --ipc=host --group-add "$render_group" --volume "$data_root:/artifacts" --env NODE_OPTIONS=--max-old-space-size=16384 --env GLYPHCSS_REFERENCE_TIMEOUT_MS=1800000 --env GLYPHCSS_WEBGPU_PRESENTATION=1 --env GLYPHCSS_REFERENCE_HEADFUL=1 --env VULKAN_ICD_FILENAMES=/etc/vulkan/icd.d/nvidia_icd.json --env "GLYPHCSS_WEBGPU_RUN_DIR=/artifacts/reference-browser/runs/$run_id" --entrypoint bash "$image_id" -lc 'Xvfb :99 -screen 0 1280x720x24 -nolisten tcp >/tmp/glyph-webgpu-xvfb.log 2>&1 & xvfb_pid=$!; chrome_root=$(mktemp -d); trap "rm -rf $chrome_root; kill $xvfb_pid" EXIT; for _ in {1..100}; do test -S /tmp/.X11-unix/X99 && break; sleep .1; done; test -S /tmp/.X11-unix/X99; unzip -q "$GLYPHCSS_REFERENCE_CHROMIUM_ARCHIVE" -d "$chrome_root"; export GLYPHCSS_REFERENCE_CHROMIUM="$chrome_root/chrome-linux64/chrome"; "$GLYPHCSS_REFERENCE_CHROMIUM" --version | grep -Ex "Google Chrome for Testing 140\\.0\\.7339\\.80 *"; nvidia-smi --query-gpu=name,driver_version,memory.total,uuid --format=csv,noheader >"$GLYPHCSS_WEBGPU_RUN_DIR/gpu.txt"; DISPLAY=:99 pnpm --filter @glyphcss/ascii-image-generation test:browser -- "reprojection-webgpu$" >"$GLYPHCSS_WEBGPU_RUN_DIR/lifecycle-test.log" 2>&1'
docker --context "$context" run --rm --entrypoint node --volume "$data_root:/artifacts" --env "RUN_DIR=/artifacts/reference-browser/runs/$run_id" --env "SOURCE_ARCHIVE_SHA256=$source_archive_sha256" --env "SOURCE_FILE_SET_SHA256=$source_file_set_sha256" --env "IMAGE_ID=$image_id" --env "PARITY_MANIFEST_SHA256=$parity_manifest_sha256" --env "PARITY_RUN_ID=$parity_run_id" "$base_image" -e 'const fs=require("fs"), c=require("crypto"), d=process.env.RUN_DIR, sha=n=>c.createHash("sha256").update(fs.readFileSync(`${d}/${n}`)).digest("hex"), source={archiveSha256:process.env.SOURCE_ARCHIVE_SHA256,fileSetSha256:process.env.SOURCE_FILE_SET_SHA256,imageId:process.env.IMAGE_ID}, report={schemaVersion:"glyph-webgpu-lifecycle-diagnostic/v1",diagnosticOnly:true,acceptance:false,browser:{version:"140.0.7339.80"},test:{title:"reprojection-webgpu",passed:true},parity:{runId:process.env.PARITY_RUN_ID,manifestSha256:process.env.PARITY_MANIFEST_SHA256},source,hashes:{testLog:sha("lifecycle-test.log"),gpu:sha("gpu.txt")}}, text=JSON.stringify(report,null,2)+"\n", reportSha256=c.createHash("sha256").update(text).digest("hex"); fs.writeFileSync(`${d}/lifecycle-report.json`,text); fs.writeFileSync(`${d}/lifecycle-report.json.sha256`,`${reportSha256}  ${d}/lifecycle-report.json\n`); fs.writeFileSync(`${d}/run-manifest.json`,JSON.stringify({schemaVersion:"glyph-webgpu-lifecycle-run/v1",diagnosticOnly:true,acceptance:false,command:"pnpm --filter @glyphcss/ascii-image-generation test:browser -- \"reprojection-webgpu$\"",reportSha256,...report},null,2)+"\n");'
printf 'WebGPU lifecycle diagnostic: %s\n' "$run_dir"
