/**
 * Colour-font atlas — the `colorEncoding: "atlas"` foundation.
 *
 * Background (measured, see `bench/color-font-atlas.md` on
 * `spike/color-font-atlas`, not re-derived here): encoding `(glyph, colour)`
 * pairs as Private Use Area code points in a COLR/CPAL font lets the
 * rasterizer write ONE text node (`<pre>.textContent`) instead of one
 * `<span>` per colour run — 2.7-9.4x FPS, main-thread work down 4.8-6.5x,
 * 20,948 DOM nodes -> 9 at equal visual output.
 *
 * This module owns exactly three things:
 *   1. The universal glyph set + PUA mapping scheme (this file).
 *   2. The checked-in font artifact (`../../assets/glyph-atlas/atlas.json`,
 *      generated by `../../assets/glyph-atlas/build-atlas.py` — NOT compiled
 *      at runtime, see below).
 *   3. `@font-face` / `@font-palette-values` CSS text emission.
 *
 * It does NOT decide palette content (deliberately out of scope — a scene
 * hands this module a palette it already derived) and it does NOT touch the
 * DOM (`createGlyphScene.ts` is the one caller that injects the emitted CSS).
 *
 * ── PUA mapping scheme ──────────────────────────────────────────────────
 *
 * `codePoint = atlas.puaStart + paletteSlot * atlas.glyphCount + glyphIndex`
 *
 * `glyphIndex` is the glyph's position in `atlas.glyphs` (fixed, checked in).
 * `paletteSlot` is a POSITION in the caller's palette array — never a colour
 * VALUE. This is load-bearing, not incidental: `@font-palette-values` /
 * `override-colors` recolours the whole atlas in ~0.4ms without touching the
 * font file (measured in the spike), so a scene can swap which concrete
 * colour slot `N` resolves to — on every frame, or by switching to a
 * different precomputed `@font-palette-values` block (a hue-rotation bank,
 * for instance) — WITHOUT re-encoding a single already-rasterized `<pre>`
 * cell or rebuilding the font. If a code point instead baked in an actual
 * RGB value, every palette change would require re-walking and re-encoding
 * the whole grid; tying it to a slot index is what keeps a palette swap a
 * pure CSS operation. `encodeGlyphAtlas` (`cells.ts`) never reads a colour's
 * numeric value when choosing a code point — only its POSITION in the
 * `palette` array passed alongside the grid.
 *
 * Blank cells (`" "`) map straight to `U+0020` — no PUA slot, no colour
 * layer, matching the spike's font (a COLR-blind fallback then renders
 * loudly-visible blanks instead of masquerading as a fast correct render).
 *
 * The atlas caps at `atlas.maxPaletteSize` (currently 31) entries: BMP
 * Private Use Area is U+E000..U+F8FF = 6,400 code points, and the checked-in
 * artifact's glyph count divides that budget across palette slots. Past the
 * BMP PUA an atlas would need a plane-15/16 code point, which is a surrogate
 * pair in JS (two UTF-16 units) — that breaks glyphcss's one-char-per-cell
 * invariant everywhere (grid indexing, `ch` CSS units, clipboard), so this
 * cap is architectural, not a size knob to raise later without a redesign.
 *
 * ── Glyph-set scope ─────────────────────────────────────────────────────
 *
 * The universal set (see `build-atlas.py` for the exact enumeration) is the
 * union of: full printable ASCII, the SOLID ramp of every named
 * `WIREFRAME_PALETTES` entry, the wireframe THIN/NORMAL/CORE tiers of only
 * the "default" and "ascii" palettes, ink mode's fixed 10-glyph set, and the
 * 11-glyph wireframe-junctions box-drawing set. It deliberately excludes
 * `charMode: "braille"`/`"quadrant"`/`"halfblock"` glyphs (two-colour-per-
 * cell or 255-glyph encoding needs its own atlas design) and the 11 other
 * named wireframe palettes' line-weight tiers (runes/math/arrows/etc. — a
 * handful of their characters aren't even in the atlas's source face). A
 * cell using a glyph or colour outside this set is NOT partially encoded —
 * see `isGlyphAtlasEncodable` in `cells.ts` for the mandatory whole-grid
 * fallback this forces.
 *
 * ── Font artifact: checked-in, not runtime-compiled ────────────────────
 *
 * The font is generated ONCE by `../../assets/glyph-atlas/build-atlas.py`
 * (Python + fontTools — the same toolchain the spike used) and checked into
 * `../../assets/glyph-atlas/atlas.json` as base64 WOFF2 (~29KB binary, ~39KB
 * base64). This module imports that JSON as a plain data module
 * (`resolveJsonModule`) — no font compilation happens in this package's
 * build (`tsup` only bundles the already-built JSON) or in the browser.
 * Regenerate the artifact by re-running the Python script whenever the
 * universal glyph set changes; nothing in `pnpm build` does this
 * automatically (Python/fontTools is not a JS toolchain dependency).
 */

import atlasManifest from "../../assets/glyph-atlas/atlas.json";

export interface GlyphFontAtlas {
  /** CSS font-family name the checked-in `@font-face` declares. */
  readonly family: string;
  /** Ordered, deduplicated universal glyph set. `glyphs[glyphIndex]` is the PUA mapping's glyph axis. */
  readonly glyphs: readonly string[];
  /** First BMP PUA code point the atlas uses (`0xE000`). */
  readonly puaStart: number;
  /** `glyphs.length` — cached for the mapping formula. */
  readonly glyphCount: number;
  /** Maximum palette slots the atlas supports without leaving the BMP PUA. */
  readonly maxPaletteSize: number;
  /** Base64-encoded WOFF2 payload — embedded inline so the atlas is self-contained (no separate font request). */
  readonly woff2Base64: string;
}

/** The one checked-in universal atlas. `fontAtlas` functions default to this. */
export const GLYPH_FONT_ATLAS: GlyphFontAtlas = Object.freeze({ ...atlasManifest });

const glyphIndexByChar: ReadonlyMap<string, number> = new Map(
  GLYPH_FONT_ATLAS.glyphs.map((glyph, index) => [glyph, index]),
);

/** Whether `glyph` has an outline in the universal atlas (space always does, trivially, via the direct `U+0020` path — see {@link glyphAtlasCodePoint}). */
export function isGlyphInFontAtlas(glyph: string, atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): boolean {
  if (glyph === " ") return true;
  return atlas === GLYPH_FONT_ATLAS ? glyphIndexByChar.has(glyph) : atlas.glyphs.includes(glyph);
}

/**
 * PUA code point for `(glyph, paletteSlot)`, or `undefined` when the glyph
 * isn't in `atlas` or `paletteSlot` is out of `[0, atlas.maxPaletteSize)`.
 * `" "` always maps to plain `U+0020` regardless of `paletteSlot` (blank
 * cells carry no colour — see the module doc).
 */
export function glyphAtlasCodePoint(
  glyph: string,
  paletteSlot: number,
  atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS,
): number | undefined {
  if (glyph === " ") return 0x20;
  if (!Number.isInteger(paletteSlot) || paletteSlot < 0 || paletteSlot >= atlas.maxPaletteSize) return undefined;
  const glyphIndex = atlas === GLYPH_FONT_ATLAS ? glyphIndexByChar.get(glyph) : atlas.glyphs.indexOf(glyph);
  if (glyphIndex === undefined || glyphIndex < 0) return undefined;
  return atlas.puaStart + paletteSlot * atlas.glyphCount + glyphIndex;
}

/**
 * Reverse of {@link glyphAtlasCodePoint}: the original glyph + palette slot
 * for a code point, or `undefined` when `codePoint` is outside the atlas's
 * occupied range. This is the copy/paste reverse-map's primitive — see
 * `website/src/lib/asciiClipboard.ts`'s `extractAsciiFromPre`.
 */
export function decodeGlyphAtlasCodePoint(
  codePoint: number,
  atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS,
): { glyph: string; paletteSlot: number } | undefined {
  if (codePoint === 0x20) return { glyph: " ", paletteSlot: -1 };
  const offset = codePoint - atlas.puaStart;
  if (offset < 0) return undefined;
  const paletteSlot = Math.floor(offset / atlas.glyphCount);
  const glyphIndex = offset % atlas.glyphCount;
  if (paletteSlot < 0 || paletteSlot >= atlas.maxPaletteSize) return undefined;
  const glyph = atlas.glyphs[glyphIndex];
  return glyph === undefined ? undefined : { glyph, paletteSlot };
}

/**
 * Decode a whole string of atlas PUA code points back to the plain glyphs
 * they encode (colour is dropped — this is for copy/paste text, not
 * re-rendering). Any code point NOT in the atlas's occupied range — plain
 * ASCII, whitespace, or anything else already in the string — passes through
 * unchanged, so this is safe to run unconditionally over `pre.textContent`
 * regardless of whether atlas encoding produced it.
 */
export function decodeGlyphAtlasText(text: string, atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): string {
  let out = "";
  for (const ch of text) {
    const cp = ch.codePointAt(0)!;
    const decoded = cp >= atlas.puaStart ? decodeGlyphAtlasCodePoint(cp, atlas) : undefined;
    out += decoded ? decoded.glyph : ch;
  }
  return out;
}

const CSS_HEX_COLOR = /^#[0-9a-fA-F]{6}$/;
/** CSS custom-ident: starts with `--`, then ident characters. Deliberately conservative (ASCII only). */
const CSS_DASHED_IDENT = /^--[a-zA-Z_][a-zA-Z0-9_-]*$/;

function assertPaletteName(name: string): void {
  if (!CSS_DASHED_IDENT.test(name)) {
    throw new TypeError(`glyphcss: font-atlas palette name must be a CSS custom ident like "--my-palette" (got ${JSON.stringify(name)}).`);
  }
}

function assertPaletteColors(colors: readonly string[], atlas: GlyphFontAtlas): void {
  if (colors.length === 0) throw new RangeError("glyphcss: font-atlas palette must have at least one color.");
  if (colors.length > atlas.maxPaletteSize) {
    throw new RangeError(`glyphcss: font-atlas palette has ${colors.length} colors, exceeding this atlas's maxPaletteSize (${atlas.maxPaletteSize}).`);
  }
  for (const color of colors) {
    if (!CSS_HEX_COLOR.test(color)) {
      throw new TypeError(`glyphcss: font-atlas palette colors must be #rrggbb (got ${JSON.stringify(color)}).`);
    }
  }
}

/**
 * `@font-face` CSS text for the checked-in atlas, with the WOFF2 payload
 * inlined as a `data:` URI — self-contained, no separate font request.
 * Idempotent to inject repeatedly (same text every call for the same atlas).
 */
export function buildGlyphAtlasFontFaceCss(atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): string {
  return `@font-face{font-family:"${atlas.family}";src:url(data:font/woff2;base64,${atlas.woff2Base64}) format("woff2");font-display:block;}`;
}

/**
 * `@font-palette-values` CSS text mapping `colors[i]` onto palette slot `i`
 * via `override-colors` — this is the ONLY place a concrete colour VALUE
 * enters the atlas pipeline; the PUA text itself never does (see the module
 * doc). `paletteName` must be a CSS custom ident (`"--foo"`); pass it as the
 * `font-palette` value on the element using the atlas font. Re-declaring
 * this per frame is measured at ~0.4ms regardless of `colors.length` — cheap
 * enough for a scene to call this every render, or for a caller to
 * precompute a whole bank of named blocks (e.g. hue-rotated variants of one
 * base palette) and pick which name to reference per frame without touching
 * this function again.
 */
export function buildGlyphAtlasFontPaletteValuesCss(
  paletteName: string,
  colors: readonly string[],
  atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS,
): string {
  assertPaletteName(paletteName);
  assertPaletteColors(colors, atlas);
  const overrides = colors.map((c, i) => `${i} ${c}`).join(", ");
  return `@font-palette-values ${paletteName}{font-family:"${atlas.family}";override-colors:${overrides};}`;
}
