/**
 * Colour-font atlas — the `colorEncoding: "atlas"` foundation.
 *
 * Background (measured, see `bench/color-font-atlas.md` on
 * `spike/color-font-atlas`, not re-derived here): encoding `(glyph, colour)`
 * pairs as Private Use Area code points in a COLR/CPAL font lets the
 * rasterizer write ONE text node (`<pre>.textContent`) instead of one
 * `<span>` per colour run — 2.7-9.4x FPS, main-thread work down 4.8-6.5x,
 * 20,948 DOM nodes -> 9 at equal visual output.
 *
 * This module owns exactly three things:
 *   1. The universal glyph set + PUA mapping scheme (this file).
 *   2. The checked-in font artifact (`../../assets/glyph-atlas/atlas.json`,
 *      generated by `../../assets/glyph-atlas/build-atlas.py` — NOT compiled
 *      at runtime, see below).
 *   3. `@font-face` / `@font-palette-values` CSS text emission.
 *
 * It does NOT decide palette content (deliberately out of scope — a scene
 * hands this module a palette it already derived) and it does NOT touch the
 * DOM (`createGlyphScene.ts` is the one caller that injects the emitted CSS).
 *
 * ── PUA mapping scheme ──────────────────────────────────────────────────
 *
 * `codePoint = atlas.puaStart + paletteSlot * atlas.glyphCount + glyphIndex`
 *
 * `glyphIndex` is the glyph's position in `atlas.glyphs` (fixed, checked in).
 * `paletteSlot` is a POSITION in the caller's palette array — never a colour
 * VALUE. This is load-bearing, not incidental: `@font-palette-values` /
 * `override-colors` recolours the whole atlas in ~0.4ms without touching the
 * font file (measured in the spike), so a scene can swap which concrete
 * colour slot `N` resolves to — on every frame, or by switching to a
 * different precomputed `@font-palette-values` block (a hue-rotation bank,
 * for instance) — WITHOUT re-encoding a single already-rasterized `<pre>`
 * cell or rebuilding the font. If a code point instead baked in an actual
 * RGB value, every palette change would require re-walking and re-encoding
 * the whole grid; tying it to a slot index is what keeps a palette swap a
 * pure CSS operation. `encodeGlyphAtlas` (`cells.ts`) never reads a colour's
 * numeric value when choosing a code point — only its POSITION in the
 * `palette` array passed alongside the grid.
 *
 * Blank cells (`" "`) map straight to `U+0020` — no PUA slot, no colour
 * layer, matching the spike's font (a COLR-blind fallback then renders
 * loudly-visible blanks instead of masquerading as a fast correct render).
 *
 * The atlas caps at `atlas.maxPaletteSize` (currently 30, at 212 glyphs) BMP
 * Private Use Area is U+E000..U+F8FF = 6,400 code points, and the checked-in
 * artifact's glyph count divides that budget across palette slots — today
 * that division (30) is the actual binding constraint, not the 31-slot
 * ceiling `build-atlas.py`'s own `MAX_PALETTE_SIZE_CAP` still allows; adding
 * more glyphs to the universal set narrows `maxPaletteSize` further. Past the
 * BMP PUA an atlas would need a plane-15/16 code point, which is a surrogate
 * pair in JS (two UTF-16 units) — that breaks glyphcss's one-char-per-cell
 * invariant everywhere (grid indexing, `ch` CSS units, clipboard), so this
 * cap is architectural, not a size knob to raise later without a redesign.
 *
 * ── Glyph-set scope ─────────────────────────────────────────────────────
 *
 * The universal set (see `build-atlas.py` for the exact enumeration) is the
 * union of: full printable ASCII, the 24 Greek capitals, the SOLID ramp of
 * EVERY named `WIREFRAME_PALETTES` entry (including "dots"/"braille"/
 * "runes" — all of it, not just what the primary source face happens to
 * contain), the wireframe THIN/NORMAL/CORE tiers of only the "default" and
 * "ascii" palettes, ink mode's fixed 10-glyph set, and the 11-glyph
 * wireframe-junctions box-drawing set. It deliberately excludes `charMode:
 * "braille"`/`"quadrant"`/`"halfblock"` glyphs (two-colour-per-cell or
 * 255-glyph encoding needs its own atlas design) and the 11 other named
 * wireframe palettes' non-solid line-weight tiers (runes/math/arrows/etc.) —
 * both are documented scope cuts, not a source-face limitation: every glyph
 * IN scope resolves from one of the atlas's three source faces (see below),
 * and `build-atlas.py`'s own glyph-set builder hard-fails the build, naming
 * the glyph, if an in-scope character resolves from none of them — it used
 * to drop such a glyph silently instead, which is how a 22-glyph gap (the
 * "default" palette's `normal` tier and the "dots"/"braille"/"runes"
 * palettes' `solid` ramps) went unnoticed for a number of revisions. A cell
 * using a glyph or colour outside this documented scope is NOT partially
 * encoded — see `isGlyphAtlasEncodable` in `cells.ts` for the mandatory
 * whole-grid fallback this forces.
 *
 * ── Font artifact: checked-in, not runtime-compiled, LAZILY loaded ──────
 *
 * The font is generated ONCE by `../../assets/glyph-atlas/build-atlas.py`
 * (Python + fontTools — the same toolchain the spike used) from THREE source
 * faces: Menlo (a macOS system font, not vendored — the primary source for
 * every glyph it covers, and still why running the script requires a Mac or
 * a copy of Menlo.ttc) plus two vendored, redistributable fallback faces
 * under `../../assets/glyph-atlas/sources/` (DejaVu Sans, Bitstream Vera
 * License; Noto Sans Runic, SIL Open Font License) for the glyphs Menlo
 * lacks — every fallback outline is scaled into Menlo's em square and
 * advance box and has its `hmtx` advance forced to Menlo's own, so an
 * imported glyph can never desync the monospace grid. The build writes TWO
 * checked-in artifacts, which is load-bearing:
 *
 *   `../../assets/glyph-atlas/atlas.json`      — metadata (~1.8KB), imported
 *      STATICALLY below because the PUA encode/decode formula needs `glyphs`,
 *      `puaStart`, `glyphCount` and `maxPaletteSize` synchronously on every
 *      frame (and `decodeGlyphAtlasText` runs on plain "spans" output too).
 *   `../../assets/glyph-atlas/atlas-font.json` — base64 WOFF2 (~49KB), reached
 *      ONLY through `import("./fontAtlasPayload")` in {@link loadGlyphAtlasFontPayload}.
 *
 * The payload was previously a field of the one manifest, which put 44KB of
 * base64 — 18% of `dist/index.js` — into every consumer's bundle whether or
 * not they ever set `colorEncoding: "atlas"`. Splitting the artifact is what
 * makes the payload a separate chunk (`tsup`'s `splitting: true`), so a
 * "spans" consumer never downloads or parses it. Do not add a static import
 * of `./fontAtlasPayload` anywhere — one would silently re-merge the chunk.
 *
 * No font compilation happens in this package's build (`tsup` only bundles
 * the already-built JSON) or in the browser. Regenerate both artifacts by
 * re-running the Python script whenever the universal glyph set changes;
 * nothing in `pnpm build` does this automatically (Python/fontTools is not a
 * JS toolchain dependency).
 *
 * ── The async transition ────────────────────────────────────────────────
 *
 * Because the payload arrives a microtask-or-more after a scene asks for
 * `colorEncoding: "atlas"`, there is a window where the encoder MUST NOT emit
 * PUA: the atlas family does not exist yet, so PUA code points would render
 * as tofu boxes in the fallback monospace face. `createGlyphScene` therefore
 * renders SPANS (the already-correct fallback the encoder falls back to for
 * an out-of-atlas glyph) until {@link glyphAtlasFontPayload} is non-undefined,
 * and re-renders once it is. A load failure resolves `null` and warns once,
 * pinning that session to spans — never a broken render.
 */

import atlasManifest from "../../assets/glyph-atlas/atlas.json";
import asciiAtlasManifest from "../../assets/glyph-atlas/ascii-atlas.json";

export interface GlyphFontAtlas {
  /** CSS font-family name the checked-in `@font-face` declares. */
  readonly family: string;
  /** Ordered, deduplicated universal glyph set. `glyphs[glyphIndex]` is the PUA mapping's glyph axis. */
  readonly glyphs: readonly string[];
  /** First BMP PUA code point the atlas uses (`0xE000`). */
  readonly puaStart: number;
  /** `glyphs.length` — cached for the mapping formula. */
  readonly glyphCount: number;
  /** Maximum palette slots the atlas supports without leaving the BMP PUA. */
  readonly maxPaletteSize: number;
}

/**
 * The checked-in UNIVERSAL atlas's METADATA. `fontAtlas` functions default
 * to this. It deliberately carries no font bytes — see the module doc; the
 * WOFF2 payload arrives separately through {@link loadGlyphAtlasFontPayload}.
 */
export const GLYPH_FONT_ATLAS: GlyphFontAtlas = Object.freeze({ ...atlasManifest });

/**
 * The checked-in ASCII-ONLY atlas variant: printable ASCII minus space, 94
 * glyphs — which frees the same 6,400-code-point BMP PUA budget for
 * `6400 // 94 = 68` palette slots instead of the universal atlas's 30. Same
 * mapping scheme, same PUA range, DIFFERENT font family, so both variants can
 * coexist in one document.
 *
 * This is a COLOUR-resolution trade, opt-in per scene via
 * `GlyphSceneOptions.fontAtlas`: a scene whose glyphs are all ASCII (a solid
 * `detail`-ramp render, say) never uses the universal set's Greek/braille/
 * box-drawing axis, and 2.3x the palette slots is where median-cut
 * quantization error actually goes down. The universal atlas's 31-slot
 * practical cap was its own budget division (6400 / 212 = 30), not a CPAL or
 * `override-colors` engine limit. A scene on this variant whose frame needs
 * any non-ASCII glyph falls back to the span encoder for that frame — the
 * same whole-grid fallback the universal atlas applies to ITS out-of-scope
 * glyphs (braille charMode, exotic wireframe palettes).
 *
 * Nothing defaults to this variant; every existing caller stays on
 * {@link GLYPH_FONT_ATLAS} untouched.
 */
export const GLYPH_FONT_ATLAS_ASCII: GlyphFontAtlas = Object.freeze({ ...asciiAtlasManifest });

/** Every atlas variant this package ships, in declaration order. */
const SHIPPED_ATLASES: readonly GlyphFontAtlas[] = Object.freeze([GLYPH_FONT_ATLAS, GLYPH_FONT_ATLAS_ASCII]);

/**
 * Which shipped atlas a `<pre>`'s CSS `font-family` names, or `undefined` when
 * the stack names none of them.
 *
 * Both shipped atlases occupy the SAME PUA range from `puaStart` 0xE000 with
 * different `glyphCount` moduli (universal 212, ASCII 94), so a code point
 * alone does not identify a glyph — decoding one against the wrong variant
 * yields a different, silently wrong character. Disjoint ranges cannot fix
 * that: 94 x 68 = 6392 of the BMP PUA's 6400 code points are already spoken
 * for. The `font-family` the renderer pins on each output `<pre>` is the one
 * per-element record of which atlas actually painted it, which makes it the
 * decoder's key — and per-`<pre>`, so a copy spanning two scenes on different
 * variants stays correct.
 *
 * Parsed as a font stack rather than matched by substring: `"GlyphCssAtlas"`
 * is a prefix of `"GlyphCssAtlasAscii"`, so a substring test resolves the
 * ASCII atlas to the universal one.
 */
export function glyphAtlasForFamily(fontFamily: string | null | undefined): GlyphFontAtlas | undefined {
  if (!fontFamily) return undefined;
  for (const entry of fontFamily.split(",")) {
    const trimmed = entry.trim();
    const quoted = /^"(.*)"$|^'(.*)'$/.exec(trimmed);
    const name = quoted ? (quoted[1] ?? quoted[2]!) : trimmed;
    const atlas = SHIPPED_ATLASES.find((candidate) => candidate.family === name);
    if (atlas) return atlas;
  }
  return undefined;
}

// Per-atlas glyph→index memo. The universal atlas had a dedicated module-level
// map; keying by atlas object keeps that O(1) lookup for BOTH shipped variants
// (and any caller-supplied atlas) without a linear `indexOf` per cell — the
// encode path calls this once per non-blank cell.
const glyphIndexByCharPerAtlas = new WeakMap<GlyphFontAtlas, ReadonlyMap<string, number>>();
function glyphIndexMap(atlas: GlyphFontAtlas): ReadonlyMap<string, number> {
  let map = glyphIndexByCharPerAtlas.get(atlas);
  if (!map) {
    map = new Map(atlas.glyphs.map((glyph, index) => [glyph, index]));
    glyphIndexByCharPerAtlas.set(atlas, map);
  }
  return map;
}

/** Whether `glyph` has an outline in the atlas (space always does, trivially, via the direct `U+0020` path — see {@link glyphAtlasCodePoint}). */
export function isGlyphInFontAtlas(glyph: string, atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): boolean {
  if (glyph === " ") return true;
  return glyphIndexMap(atlas).has(glyph);
}

/**
 * PUA code point for `(glyph, paletteSlot)`, or `undefined` when the glyph
 * isn't in `atlas` or `paletteSlot` is out of `[0, atlas.maxPaletteSize)`.
 * `" "` always maps to plain `U+0020` regardless of `paletteSlot` (blank
 * cells carry no colour — see the module doc).
 */
export function glyphAtlasCodePoint(
  glyph: string,
  paletteSlot: number,
  atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS,
): number | undefined {
  if (glyph === " ") return 0x20;
  if (!Number.isInteger(paletteSlot) || paletteSlot < 0 || paletteSlot >= atlas.maxPaletteSize) return undefined;
  const glyphIndex = glyphIndexMap(atlas).get(glyph);
  if (glyphIndex === undefined) return undefined;
  return atlas.puaStart + paletteSlot * atlas.glyphCount + glyphIndex;
}

/**
 * Reverse of {@link glyphAtlasCodePoint}: the original glyph + palette slot
 * for a code point, or `undefined` when `codePoint` is outside the atlas's
 * occupied range. This is the copy/paste reverse-map's primitive — see
 * `website/src/lib/asciiClipboard.ts`'s `extractAsciiFromPre`.
 */
export function decodeGlyphAtlasCodePoint(
  codePoint: number,
  atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS,
): { glyph: string; paletteSlot: number } | undefined {
  if (codePoint === 0x20) return { glyph: " ", paletteSlot: -1 };
  const offset = codePoint - atlas.puaStart;
  if (offset < 0) return undefined;
  const paletteSlot = Math.floor(offset / atlas.glyphCount);
  const glyphIndex = offset % atlas.glyphCount;
  if (paletteSlot < 0 || paletteSlot >= atlas.maxPaletteSize) return undefined;
  const glyph = atlas.glyphs[glyphIndex];
  return glyph === undefined ? undefined : { glyph, paletteSlot };
}

/**
 * Decode a whole string of atlas PUA code points back to the plain glyphs
 * they encode (colour is dropped — this is for copy/paste text, not
 * re-rendering). Any code point NOT in the atlas's occupied range — plain
 * ASCII, whitespace, or anything else already in the string — passes through
 * unchanged, so this is safe to run unconditionally over `pre.textContent`
 * regardless of whether atlas encoding produced it.
 */
export function decodeGlyphAtlasText(text: string, atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): string {
  let out = "";
  for (const ch of text) {
    const cp = ch.codePointAt(0)!;
    const decoded = cp >= atlas.puaStart ? decodeGlyphAtlasCodePoint(cp, atlas) : undefined;
    out += decoded ? decoded.glyph : ch;
  }
  return out;
}

const CSS_HEX_COLOR = /^#[0-9a-fA-F]{6}$/;
/** CSS custom-ident: starts with `--`, then ident characters. Deliberately conservative (ASCII only). */
const CSS_DASHED_IDENT = /^--[a-zA-Z_][a-zA-Z0-9_-]*$/;

function assertPaletteName(name: string): void {
  if (!CSS_DASHED_IDENT.test(name)) {
    throw new TypeError(`glyphcss: font-atlas palette name must be a CSS custom ident like "--my-palette" (got ${JSON.stringify(name)}).`);
  }
}

function assertPaletteColors(colors: readonly string[], atlas: GlyphFontAtlas): void {
  if (colors.length === 0) throw new RangeError("glyphcss: font-atlas palette must have at least one color.");
  if (colors.length > atlas.maxPaletteSize) {
    throw new RangeError(`glyphcss: font-atlas palette has ${colors.length} colors, exceeding this atlas's maxPaletteSize (${atlas.maxPaletteSize}).`);
  }
  for (const color of colors) {
    if (!CSS_HEX_COLOR.test(color)) {
      throw new TypeError(`glyphcss: font-atlas palette colors must be #rrggbb (got ${JSON.stringify(color)}).`);
    }
  }
}

// ── Lazy WOFF2 payload ───────────────────────────────────────────────────

/** Lifecycle of the process-wide atlas WOFF2 payload. See {@link glyphAtlasFontLoadState}. */
export type GlyphAtlasFontLoadState = "idle" | "loading" | "ready" | "failed";

type GlyphAtlasFontPayloadModule = { readonly GLYPH_FONT_ATLAS_WOFF2_BASE64: string };

/**
 * Per-atlas payload lifecycle, keyed by atlas IDENTITY, so each shipped
 * variant loads its own chunk exactly once while the OTHER variant's chunk is
 * never touched. Keying by `family` instead would hand a caller-built atlas
 * that happens to reuse a shipped family name the SHIPPED WOFF2, whose glyph
 * indices are not that atlas's — silently wrong glyphs rather than the loud
 * "no payload registered" rejection below.
 */
interface PayloadEntry {
  importer: () => Promise<GlyphAtlasFontPayloadModule>;
  state: GlyphAtlasFontLoadState;
  payload: string | undefined;
  promise: Promise<string | null> | null;
}

const DEFAULT_PAYLOAD_IMPORTERS: ReadonlyMap<GlyphFontAtlas, () => Promise<GlyphAtlasFontPayloadModule>> = new Map([
  // Both dynamic-only: each payload stays its own lazily-split chunk — see the
  // module doc's warning against static imports of a payload module.
  [GLYPH_FONT_ATLAS, () => import("./fontAtlasPayload")],
  [GLYPH_FONT_ATLAS_ASCII, () => import("./fontAtlasAsciiPayload")],
]);

let payloadEntries = new WeakMap<GlyphFontAtlas, PayloadEntry>();

function payloadEntry(atlas: GlyphFontAtlas): PayloadEntry {
  let entry = payloadEntries.get(atlas);
  if (!entry) {
    const importer = DEFAULT_PAYLOAD_IMPORTERS.get(atlas);
    entry = {
      importer: importer
        ?? (() => Promise.reject(new Error(`glyphcss: no WOFF2 payload is registered for font atlas family ${JSON.stringify(atlas.family)}.`))),
      state: "idle",
      payload: undefined,
      promise: null,
    };
    payloadEntries.set(atlas, entry);
  }
  return entry;
}

/**
 * Load an atlas's base64 WOFF2 on demand. Idempotent and SHARED per atlas:
 * every caller after the first awaits the same promise, so ten scenes on one
 * page trigger one import, not ten. Resolves `null` — never rejects — when the
 * payload cannot be loaded, having warned once; the caller's contract is to
 * degrade to `colorEncoding: "spans"` for the rest of the session.
 */
export function loadGlyphAtlasFontPayload(atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): Promise<string | null> {
  const entry = payloadEntry(atlas);
  if (entry.promise) return entry.promise;
  entry.state = "loading";
  entry.promise = entry.importer().then(
    (mod) => {
      entry.payload = mod.GLYPH_FONT_ATLAS_WOFF2_BASE64;
      entry.state = "ready";
      return entry.payload;
    },
    (error: unknown) => {
      entry.state = "failed";
      console.warn(
        "glyphcss: could not load the colour-font atlas payload; colorEncoding \"atlas\" will render as \"spans\" for the rest of this session.",
        error,
      );
      return null;
    },
  );
  return entry.promise;
}

/**
 * The loaded payload, or `undefined` while it is still loading / after it
 * failed. Synchronous by design: the render path needs a non-blocking answer
 * to "may I emit PUA this frame?" (see the module doc's async-transition
 * section), and `undefined` means "no — encode spans".
 */
export function glyphAtlasFontPayload(atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): string | undefined {
  return payloadEntry(atlas).payload;
}

/** Current lifecycle of an atlas's shared payload load. `"failed"` is terminal for the session. */
export function glyphAtlasFontLoadState(atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): GlyphAtlasFontLoadState {
  return payloadEntry(atlas).state;
}

/**
 * Swap the UNIVERSAL atlas's payload importer and reset its load state.
 * Test-only seam — not exported from the package index. Scoped to the
 * universal atlas, exactly as before the ASCII variant existed; the ASCII
 * entry is reset alongside so a test that swaps importers starts clean.
 */
export function setGlyphAtlasFontPayloadImportForTests(
  next: (() => Promise<GlyphAtlasFontPayloadModule>) | null,
): void {
  payloadEntries = new WeakMap();
  if (next) {
    payloadEntries.set(GLYPH_FONT_ATLAS, {
      importer: next, state: "idle", payload: undefined, promise: null,
    });
  }
}

/**
 * `@font-face` CSS text for the checked-in atlas, with `woff2Base64` inlined
 * as a `data:` URI — self-contained, no separate font request. Idempotent to
 * inject repeatedly (same text every call for the same payload + atlas).
 *
 * Takes the payload as an argument rather than reading it off `atlas`: the
 * atlas metadata is statically bundled but the payload is not (module doc), so
 * a caller has to have obtained it — from {@link loadGlyphAtlasFontFaceCss},
 * {@link loadGlyphAtlasFontPayload}, or its own build step — before it can
 * emit a `@font-face` that actually carries a font. That is deliberate: the
 * failure mode this signature rules out is a static/CodePen export silently
 * shipping a `@font-face` with an empty `src`.
 */
export function buildGlyphAtlasFontFaceCss(woff2Base64: string, atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): string {
  if (typeof woff2Base64 !== "string" || woff2Base64.length === 0) {
    throw new TypeError("glyphcss: buildGlyphAtlasFontFaceCss needs the atlas WOFF2 payload — await loadGlyphAtlasFontPayload() (or loadGlyphAtlasFontFaceCss()) first.");
  }
  return `@font-face{font-family:"${atlas.family}";src:url(data:font/woff2;base64,${woff2Base64}) format("woff2");font-display:block;}`;
}

/**
 * `@font-face` CSS text, loading the payload on demand. This is the awaited
 * path a static / CodePen / SSR export uses to inline the font into a
 * self-contained artifact. Unlike {@link loadGlyphAtlasFontPayload} it REJECTS
 * when the payload is unavailable — an export that quietly emitted a pen with
 * no font would look correct in code review and render tofu in the browser,
 * so the loud failure is the right one for a build-time caller.
 */
export async function loadGlyphAtlasFontFaceCss(atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS): Promise<string> {
  // Must be THIS atlas's payload: the family below comes from `atlas`, so
  // loading the default here would emit one variant's family over another's
  // font bytes, and every PUA code point would resolve against the wrong
  // glyph indices.
  const base64 = await loadGlyphAtlasFontPayload(atlas);
  if (base64 === null) {
    throw new Error("glyphcss: the colour-font atlas payload could not be loaded, so no @font-face can be emitted for it.");
  }
  return buildGlyphAtlasFontFaceCss(base64, atlas);
}

/**
 * `@font-palette-values` CSS text mapping `colors[i]` onto palette slot `i`
 * via `override-colors` — this is the ONLY place a concrete colour VALUE
 * enters the atlas pipeline; the PUA text itself never does (see the module
 * doc). `paletteName` must be a CSS custom ident (`"--foo"`); pass it as the
 * `font-palette` value on the element using the atlas font. Re-declaring
 * this per frame is measured at ~0.4ms regardless of `colors.length` — cheap
 * enough for a scene to call this every render, or for a caller to
 * precompute a whole bank of named blocks (e.g. hue-rotated variants of one
 * base palette) and pick which name to reference per frame without touching
 * this function again.
 */
export function buildGlyphAtlasFontPaletteValuesCss(
  paletteName: string,
  colors: readonly string[],
  atlas: GlyphFontAtlas = GLYPH_FONT_ATLAS,
): string {
  assertPaletteName(paletteName);
  assertPaletteColors(colors, atlas);
  const overrides = colors.map((c, i) => `${i} ${c}`).join(", ");
  return `@font-palette-values ${paletteName}{font-family:"${atlas.family}";override-colors:${overrides};}`;
}
